In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', -1)

/var/folders/mx/rxqrr3wj24q81gylcgl4fjvh0000gn/T/ipykernel_78270/2870173724.py:8: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  pd.set_option('display.max_colwidth', -1)

In [2]:
fbs = pd.read_excel('./list_fbs.xlsx')

In [3]:
fbs.head()

,Unnamed: 0,id_uni,id_fak,name_fb,city,street_nr,plz,total_doz,total_stud,total_stud_ma,support_start,tframe_grad_ba,tframe_grad_ma,lon,lat,int_ba,int_ma,foreign_spot,sup_doz,sup_in_studies,curriculum,students_orga,exams,research_conn,offer_joborientation,supp_exchange,faculties,bib,it_infrastructure,grade_overall,total_students_la,la_studies
0,0.0,2,30546,Philologische Fakultät an der Uni Freiburg,Freiburg,Rempartstraße 15,79085,keine Angabe,470 *,130 *,keine Angaben,"73,3 % *","26,7 % *",7.847936,47.998253,Indikator nicht ausgewiesen,Indikator nicht ausgewiesen,keine Angaben,keine Befragung,keine Befragung,keine Befragung,keine Befragung,keine Befragung,keine Befragung,keine Befragung,keine Befragung,keine Befragung,keine Befragung,keine Befragung,keine Befragung,330 *,keine Angaben
1,1.0,2,1200001,Fakultät für Chemie und Pharmazie an der Uni Freiburg,Freiburg,Albertstr. 21,79104,NaN,90,NaN,Nur Master SG,keine Angaben,"53,7 %",7.847936,47.998253,NaN,NaN,NaN,Unterstützung im Studium,NaN,Studienorganisation,NaN,Laborpraktika,Angebote zur Berufsorientierung,NaN,Räume,NaN,IT-Infrastruktur,NaN,Weitere Studiengänge am Fachbereich,NaN,NaN
2,2.0,2,420102,Fakultät für Biologie an der Uni Freiburg,Freiburg,Schänzlestraße 1,79104,NaN,1.260,NaN,11/14 Punkten,"88,2 %","54,9 %",7.847936,47.998253,NaN,NaN,NaN,"2,4",Ranggruppe nicht eindeutig zuweisbar,"2,5","1,6 *","2,4","2,1",Ranggruppe nicht eindeutig zuweisbar,"2,4","1,7","1,8 *","2,3 *","2,2",263,"Abschlüsse: Zwei-Fach-Bachelor, Master of Education; Lehramtstypen: LA Sek II/Gym"
3,3.0,2,600799,Wirtschafts- und Verhaltenswissenschaftliche Fakultät an der Uni Freiburg,Freiburg,Platz der Alten Synagoge,79098,NaN,530 *,160 *,keine Angaben,"83,1 % *","43,5 % *",7.847936,47.998253,NaN,NaN,keine Angabe,NaN,Lehrangebot,NaN,Prüfungen,NaN,Angebote zur Berufsorientierung,NaN,Räume,NaN,IT-Infrastruktur,NaN,Betreuung durch Lehrende,NaN,NaN
4,4.0,2,200001,Fakultät für Chemie und Pharmazie an der Uni Freiburg,Freiburg,Albertstr. 21,79104,NaN,940,NaN,7/14 Punkten,"78,9 %",NaN,7.847936,47.998253,NaN,NaN,NaN,NaN,Fallzahl kleiner 15,NaN,Fallzahl kleiner 15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"2,5",NaN,NaN

In [4]:
fbs.drop(labels = 'Unnamed: 0', axis = 1, inplace = True)

In [5]:
#studis['name_stud'] = studis['name_stud'].apply(lambda x: x.title())
#studis.head()

In [6]:
fbs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2251 entries, 0 to 2250
Data columns (total 31 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_uni                2251 non-null   int64
 1   id_fak                2251 non-null   int64
 2   name_fb               2251 non-null   object
 3   city                  2251 non-null   object
 4   street_nr             2250 non-null   object
 5   plz                   2251 non-null   int64
 6   total_doz             282 non-null    object
 7   total_stud            1747 non-null   object
 8   total_stud_ma         1080 non-null   object
 9   support_start         1994 non-null   object
 10  tframe_grad_ba        1554 non-null   object
 11  tframe_grad_ma        1421 non-null   object
 12  lon                   2251 non-null   float64
 13  lat                   2251 non-null   float64
 14  int_ba                702 non-null    object
 15  int_ma                610 non-null    object
 16  foreign_spot          1239 non-null   object
 17  sup_doz               1446 non-null   object
 18  sup_in_studies        1411 non-null   object
 19  curriculum            1424 non-null   object
 20  students_orga         1410 non-null   object
 21  exams                 1363 non-null   object
 22  research_conn         849 non-null    object
 23  offer_joborientation  1123 non-null   object
 24  supp_exchange         1362 non-null   object
 25  faculties             1349 non-null   object
 26  bib                   1129 non-null   object
 27  it_infrastructure     1335 non-null   object
 28  grade_overall         1451 non-null   object
 29  total_students_la     241 non-null    object
 30  la_studies            240 non-null    object
dtypes: float64(2), int64(3), object(26)
memory usage: 545.3+ KB

In [7]:
fbs.drop('total_doz', axis = 1, inplace = True)

In [8]:
fbs[fbs['total_stud']=='Anzahl Masterstudierende']

,id_uni,id_fak,name_fb,city,street_nr,plz,total_stud,total_stud_ma,support_start,tframe_grad_ba,tframe_grad_ma,lon,lat,int_ba,int_ma,foreign_spot,sup_doz,sup_in_studies,curriculum,students_orga,exams,research_conn,offer_joborientation,supp_exchange,faculties,bib,it_infrastructure,grade_overall,total_students_la,la_studies
1779,468,604155,Fakultät für Ingenieurwissenschaften an der HS Wismar,Wismar,Philipp-Müller-Straße 14,23966,Anzahl Masterstudierende,NaN,es liegen keine Daten vor,keine Angaben,keine Angaben,11.440575,53.889339,NaN,NaN,NaN,Unterstützung im Studium,Lehrangebot,Studienorganisation,Prüfungen,NaN,NaN,Praxisbezug,Räume,NaN,IT-Infrastruktur,NaN,NaN,NaN,NaN
1811,478,491021,Fachbereich Bauwesen und Geoinformation an der Jade HS/Oldenburg,Oldenburg,Ofener Straße 16,26121,Anzahl Masterstudierende,NaN,es liegen keine Daten vor,keine Angaben,keine Angaben,8.201775,53.141610,NaN,NaN,NaN,Unterstützung im Studium,Lehrangebot,Studienorganisation,Prüfungen,NaN,NaN,Praxisbezug,Räume,NaN,IT-Infrastruktur,NaN,NaN,NaN,NaN

In [9]:
def to_num_or_null(x):
    try:
        return pd.to_numeric(x)
    except:
        return np.nan

In [10]:
fbs['total_stud'] = fbs['total_stud'].apply(lambda x : to_num_or_null(str(x).replace(" *", "").replace('.','')))

In [11]:
fbs['total_stud'].head(50)

0     470.0
1     90.0
2     1260.0
3     530.0
4     940.0
5     190.0
6     330.0
7     230.0
8     420.0
9     1000.0
10   NaN
11    2500.0
12    530.0
13    3080.0
14    170.0
15    720.0
16    500.0
17    570.0
18    730.0
19    440.0
20    430.0
21    1620.0
22    590.0
23    420.0
24    180.0
25    1770.0
26    1030.0
27    320.0
28    930.0
29    170.0
30    250.0
31    850.0
32    780.0
33    2790.0
34    1050.0
35    3560.0
36    780.0
37    2550.0
38    1030.0
39    880.0
40    130.0
41    530.0
42    1210.0
43    560.0
44    450.0
45   NaN
46   NaN
47   NaN
48   NaN
49    270.0
Name: total_stud, dtype: float64

In [12]:
fbs["total_stud"] =fbs["total_stud"].convert_dtypes(int)

In [13]:
fbs['total_stud_ma'] = fbs['total_stud_ma'].apply(lambda x : to_num_or_null(str(x).replace(" *", "").replace('.','')))

In [14]:
fbs["total_stud_ma"] =fbs["total_stud_ma"].convert_dtypes(int)
fbs['total_stud_ma'].isnull()

0       False
1       True
2       True
3       False
4       True
5       False
6       True
7       True
8       False
9       False
10      True
11      True
12      False
13      True
14      True
15      True
16      False
17      True
18      False
19      False
20      True
21      False
22      True
23      False
24      True
25      True
26      True
27      False
28      True
29      True
30      False
31      False
32      False
33      True
34      False
35      True
36      True
37      False
38      True
39      False
40      False
41      True
42      False
43      True
44      True
45      True
46      False
47      True
48      False
49      False
50      False
51      False
52      True
53      True
54      True
55      True
56      True
57      True
58      False
59      True
60      True
61      False
62      False
63      True
64      True
65      False
66      False
67      False
68      True
69      True
70      True
71      False
72      False
73      False
74      True
75      True
76      False
77      False
78      True
79      False
80      False
81      True
82      False
83      False
84      True
85      False
86      False
87      False
88      False
89      True
90      True
91      False
92      False
93      False
94      False
95      False
96      False
97      True
98      True
99      False
100     True
101     True
102     False
103     True
104     False
105     False
106     True
107     True
108     True
109     False
110     False
111     False
112     True
113     False
114     True
115     True
116     True
117     True
118     False
119     False
120     True
121     True
122     False
123     True
124     False
125     True
126     True
127     False
128     False
129     True
130     False
131     True
132     True
133     True
134     False
135     True
136     False
137     False
138     True
139     False
140     True
141     True
142     True
143     True
144     False
145     True
146     True
147     True
148     False
149     True
150     False
151     True
152     False
153     False
154     False
155     True
156     False
157     False
158     False
159     False
160     True
161     False
162     False
163     True
164     False
165     True
166     False
167     True
168     False
169     True
170     False
171     True
172     False
173     False
174     False
175     False
176     False
177     True
178     False
179     False
180     True
181     False
182     False
183     False
184     False
185     False
186     True
187     True
188     True
189     False
190     False
191     True
192     True
193     True
194     True
195     False
196     False
197     True
198     True
199     True
200     False
201     False
202     False
203     False
204     True
205     True
206     True
207     False
208     True
209     False
210     False
211     True
212     False
213     False
214     True
215     True
216     True
217     False
218     False
219     True
220     False
221     True
222     True
223     True
224     True
225     True
226     False
227     True
228     True
229     False
230     False
231     True
232     True
233     True
234     True
235     False
236     False
237     True
238     True
239     False
240     True
241     False
242     False
243     True
244     True
245     True
246     False
247     True
248     False
249     True
250     True
251     False
252     True
253     False
254     True
255     True
256     False
257     False
258     True
259     False
260     True
261     True
262     False
263     True
264     False
265     False
266     False
267     True
268     False
269     True
270     False
271     False
272     True
273     True
274     True
275     True
276     True
277     True
278     True
279     True
280     True
281     False
282     False
283     True
284     True
285     False
286     True
287     False
288     False
289     False
290     False
291     True
292     True
293     False
294     True
295     False
296     True
297     True
298     True
299     False
300     False
301     False
302     True
303     True
304     False
305     True
306     False
307     False
308     False
309     True
310     False
311     True
312     True
313     False
314     True
315     False
316     False
317     True
318     False
319     False
320     True
321     False
322     True
323     False
324     True
325     False
326     True
327     False
328     False
329     True
330     False
331     True
332     True
333     False
334     True
335     False
336     False
337     True
338     False
339     False
340     True
341     True
342     False
343     False
344     True
345     True
346     False
347     True
348     False
349     True
350     True
351     False
352     False
353     True
354     False
355     True
356     False
357     True
358     False
359     False
360     False
361     False
362     True
363     True
364     False
365     True
366     True
367     True
368     True
369     False
370     True
371     True
372     True
373     True
374     False
375     False
376     True
377     True
378     False
379     True
380     False
381     False
382     True
383     False
384     True
385     False
386     True
387     False
388     False
389     True
390     False
391     False
392     True
393     False
394     False
395     True
396     False
397     False
398     False
399     False
400     True
401     False
402     True
403     True
404     False
405     True
406     True
407     False
408     False
409     True
410     True
411     True
412     False
413     False
414     True
415     True
416     False
417     True
418     True
419     False
420     True
421     False
422     True
423     True
424     True
425     False
426     False
427     True
428     False
429     False
430     True
431     False
432     False
433     True
434     False
435     False
436     False
437     True
438     True
439     False
440     True
441     True
442     False
443     True
444     True
445     False
446     False
447     True
448     True
449     False
450     False
451     True
452     False
453     True
454     False
455     False
456     True
457     True
458     False
459     False
460     False
461     True
462     False
463     True
464     False
465     True
466     True
467     False
468     False
469     True
470     False
471     True
472     True
473     False
474     True
475     False
476     False
477     True
478     False
479     False
480     False
481     True
482     True
483     True
484     True
485     False
486     True
487     False
488     True
489     True
490     True
491     True
492     False
493     True
494     True
495     True
496     False
497     True
498     False
499     True
500     False
501     True
502     True
503     True
504     True
505     False
506     True
507     False
508     False
509     False
510     False
511     True
512     False
513     True
514     True
515     True
516     True
517     False
518     True
519     False
520     False
521     True
522     True
523     False
524     False
525     False
526     True
527     False
528     True
529     True
530     True
531     False
532     False
533     False
534     True
535     True
536     False
537     True
538     False
539     True
540     True
541     False
542     False
543     True
544     False
545     True
546     True
547     False
548     True
549     False
550     False
551     True
552     False
553     False
554     False
555     True
556     False
557     True
558     False
559     True
560     False
561     True
562     False
563     True
564     False
565     True
566     False
567     True
568     False
569     False
570     True
571     False
572     True
573     True
574     False
575     True
576     True
577     False
578     True
579     False
580     True
581     False
582     False
583     True
584     False
585     True
586     True
587     False
588     True
589     False
590     False
591     True
592     False
593     False
594     True
595     False
596     True
597     True
598     True
599     False
600     True
601     True
602     False
603     True
604     False
605     True
606     True
607     False
608     True
609     False
610     True
611     False
612     True
613     True
614     True
615     False
616     True
617     True
618     False
619     False
620     False
621     True
622     True
623     False
624     False
625     True
626     False
627     True
628     True
629     True
630     True
631     False
632     False
633     False
634     True
635     True
636     True
637     False
638     True
639     True
640     True
641     True
642     False
643     True
644     True
645     True
646     True
647     True
648     False
649     True
650     False
651     False
652     True
653     False
654     True
655     False
656     True
657     True
658     False
659     False
660     False
661     False
662     False
663     True
664     True
665     True
666     False
667     True
668     True
669     False
670     False
671     False
672     True
673     True
674     False
675     True
676     False
677     True
678     True
679     False
680     False
681     True
682     False
683     True
684     False
685     True
686     False
687     False
688     True
689     False
690     False
691     True
692     False
693     False
694     True
695     True
696     True
697     True
698     True
699     True
700     False
701     True
702     True
703     True
704     False
705     False
706     True
707     True
708     True
709     False
710     False
711     True
712     False
713     True
714     True
715     True
716     False
717     False
718     True
719     True
720     True
721     False
722     True
723     False
724     True
725     True
726     True
727     False
728     True
729     False
730     True
731     True
732     True
733     False
734     True
735     True
736     False
737     True
738     True
739     True
740     False
741     True
742     True
743     True
744     True
745     False
746     True
747     False
748     True
749     False
750     True
751     False
752     False
753     False
754     False
755     True
756     False
757     True
758     False
759     True
760     False
761     False
762     False
763     False
764     True
765     True
766     False
767     True
768     True
769     True
770     True
771     False
772     False
773     True
774     False
775     True
776     False
777     True
778     False
779     True
780     True
781     False
782     False
783     False
784     False
785     True
786     False
787     True
788     True
789     True
790     True
791     False
792     False
793     False
794     True
795     False
796     True
797     False
798     True
799     False
800     True
801     True
802     False
803     False
804     False
805     True
806     True
807     True
808     True
809     False
810     True
811     True
812     False
813     False
814     True
815     True
816     True
817     False
818     True
819     False
820     True
821     True
822     False
823     False
824     True
825     True
826     True
827     True
828     False
829     False
830     True
831     True
832     True
833     True
834     False
835     False
836     True
837     False
838     True
839     True
840     False
841     True
842     False
843     False
844     False
845     True
846     True
847     False
848     True
849     True
850     True
851     True
852     True
853     False
854     True
855     False
856     True
857     False
858     False
859     True
860     False
861     False
862     False
863     True
864     True
865     False
866     True
867     False
868     False
869     True
870     False
871     True
872     True
873     False
874     True
875     False
876     False
877     False
878     True
879     False
880     True
881     True
882     False
883     True
884     False
885     True
886     True
887     False
888     True
889     False
890     True
891     False
892     True
893     False
894     False
895     False
896     False
897     True
898     True
899     False
900     True
901     False
902     True
903     False
904     True
905     True
906     False
907     False
908     True
909     False
910     True
911     True
912     False
913     True
914     False
915     False
916     True
917     False
918     False
919     True
920     True
921     False
922     False
923     True
924     False
925     True
926     True
927     True
928     False
929     True
930     True
931     True
932     True
933     False
934     True
935     True
936     False
937     False
938     True
939     True
940     True
941     False
942     True
943     True
944     False
945     True
946     True
947     False
948     False
949     False
950     True
951     True
952     False
953     False
954     True
955     False
956     True
957     False
958     True
959     True
960     False
961     False
962     True
963     False
964     True
965     True
966     False
967     True
968     False
969     False
970     True
971     False
972     True
973     True
974     False
975     True
976     False
977     False
978     True
979     True
980     False
981     False
982     True
983     False
984     True
985     True
986     False
987     False
988     False
989     False
990     False
991     False
992     True
993     False
994     True
995     True
996     False
997     False
998     True
999     True
1000    True
1001    False
1002    False
1003    True
1004    False
1005    False
1006    False
1007    True
1008    True
1009    False
1010    True
1011    False
1012    False
1013    True
1014    True
1015    True
1016    False
1017    True
1018    False
1019    True
1020    False
1021    False
1022    True
1023    True
1024    True
1025    False
1026    True
1027    True
1028    False
1029    True
1030    False
1031    False
1032    False
1033    True
1034    True
1035    True
1036    True
1037    True
1038    False
1039    True
1040    True
1041    False
1042    True
1043    True
1044    False
1045    True
1046    True
1047    True
1048    True
1049    False
1050    False
1051    False
1052    True
1053    True
1054    False
1055    True
1056    True
1057    False
1058    False
1059    True
1060    True
1061    True
1062    True
1063    False
1064    True
1065    False
1066    False
1067    True
1068    False
1069    False
1070    False
1071    True
1072    False
1073    False
1074    True
1075    True
1076    False
1077    True
1078    False
1079    True
1080    True
1081    False
1082    False
1083    True
1084    False
1085    True
1086    True
1087    True
1088    False
1089    True
1090    False
1091    False
1092    True
1093    False
1094    False
1095    True
1096    True
1097    False
1098    True
1099    True
1100    False
1101    False
1102    False
1103    True
1104    True
1105    True
1106    False
1107    False
1108    True
1109    False
1110    True
1111    False
1112    True
1113    True
1114    True
1115    False
1116    False
1117    False
1118    False
1119    False
1120    False
1121    False
1122    True
1123    False
1124    True
1125    True
1126    False
1127    True
1128    True
1129    False
1130    False
1131    True
1132    False
1133    True
1134    True
1135    False
1136    True
1137    True
1138    False
1139    True
1140    False
1141    True
1142    False
1143    False
1144    True
1145    True
1146    False
1147    True
1148    False
1149    True
1150    True
1151    False
1152    False
1153    False
1154    True
1155    True
1156    False
1157    True
1158    True
1159    True
1160    True
1161    False
1162    False
1163    False
1164    True
1165    False
1166    False
1167    False
1168    True
1169    True
1170    False
1171    True
1172    False
1173    True
1174    True
1175    True
1176    False
1177    False
1178    True
1179    False
1180    True
1181    True
1182    False
1183    True
1184    False
1185    False
1186    True
1187    False
1188    True
1189    False
1190    True
1191    True
1192    False
1193    True
1194    False
1195    True
1196    True
1197    False
1198    False
1199    False
1200    True
1201    True
1202    False
1203    True
1204    False
1205    False
1206    True
1207    False
1208    False
1209    False
1210    True
1211    False
1212    False
1213    True
1214    True
1215    True
1216    False
1217    False
1218    True
1219    False
1220    False
1221    True
1222    False
1223    True
1224    True
1225    True
1226    True
1227    False
1228    True
1229    True
1230    False
1231    False
1232    True
1233    True
1234    False
1235    True
1236    False
1237    False
1238    False
1239    False
1240    True
1241    True
1242    False
1243    True
1244    True
1245    False
1246    False
1247    False
1248    False
1249    True
1250    True
1251    True
1252    False
1253    False
1254    False
1255    True
1256    True
1257    False
1258    False
1259    False
1260    True
1261    False
1262    False
1263    False
1264    False
1265    False
1266    False
1267    False
1268    True
1269    True
1270    False
1271    True
1272    True
1273    True
1274    False
1275    False
1276    True
1277    True
1278    False
1279    False
1280    False
1281    True
1282    True
1283    False
1284    True
1285    False
1286    True
1287    False
1288    False
1289    True
1290    False
1291    False
1292    True
1293    True
1294    True
1295    True
1296    False
1297    True
1298    False
1299    False
1300    True
1301    True
1302    True
1303    False
1304    False
1305    True
1306    False
1307    False
1308    True
1309    False
1310    False
1311    False
1312    False
1313    False
1314    False
1315    True
1316    True
1317    False
1318    True
1319    True
1320    False
1321    True
1322    True
1323    False
1324    False
1325    False
1326    False
1327    True
1328    False
1329    False
1330    True
1331    True
1332    False
1333    True
1334    False
1335    False
1336    True
1337    True
1338    False
1339    True
1340    True
1341    False
1342    False
1343    True
1344    True
1345    False
1346    True
1347    True
1348    False
1349    False
1350    True
1351    False
1352    True
1353    True
1354    True
1355    True
1356    True
1357    False
1358    True
1359    True
1360    False
1361    False
1362    False
1363    False
1364    True
1365    False
1366    True
1367    True
1368    False
1369    False
1370    False
1371    True
1372    False
1373    False
1374    False
1375    False
1376    True
1377    False
1378    False
1379    False
1380    True
1381    True
1382    False
1383    False
1384    False
1385    False
1386    True
1387    False
1388    False
1389    False
1390    True
1391    False
1392    True
1393    False
1394    True
1395    True
1396    False
1397    True
1398    True
1399    True
1400    False
1401    False
1402    False
1403    False
1404    True
1405    True
1406    True
1407    False
1408    True
1409    False
1410    False
1411    True
1412    False
1413    False
1414    True
1415    True
1416    True
1417    False
1418    True
1419    False
1420    False
1421    True
1422    True
1423    True
1424    False
1425    False
1426    True
1427    False
1428    False
1429    True
1430    True
1431    False
1432    True
1433    True
1434    True
1435    False
1436    False
1437    False
1438    True
1439    True
1440    False
1441    False
1442    True
1443    True
1444    False
1445    False
1446    False
1447    True
1448    True
1449    True
1450    False
1451    False
1452    True
1453    False
1454    True
1455    False
1456    False
1457    True
1458    True
1459    True
1460    True
1461    False
1462    False
1463    True
1464    True
1465    True
1466    True
1467    True
1468    False
1469    True
1470    False
1471    False
1472    False
1473    True
1474    True
1475    True
1476    False
1477    True
1478    True
1479    True
1480    True
1481    True
1482    True

In [15]:
fbs.head()

,id_uni,id_fak,name_fb,city,street_nr,plz,total_stud,total_stud_ma,support_start,tframe_grad_ba,tframe_grad_ma,lon,lat,int_ba,int_ma,foreign_spot,sup_doz,sup_in_studies,curriculum,students_orga,exams,research_conn,offer_joborientation,supp_exchange,faculties,bib,it_infrastructure,grade_overall,total_students_la,la_studies
0,2,30546,Philologische Fakultät an der Uni Freiburg,Freiburg,Rempartstraße 15,79085,470,130,keine Angaben,"73,3 % *","26,7 % *",7.847936,47.998253,Indikator nicht ausgewiesen,Indikator nicht ausgewiesen,keine Angaben,keine Befragung,keine Befragung,keine Befragung,keine Befragung,keine Befragung,keine Befragung,keine Befragung,keine Befragung,keine Befragung,keine Befragung,keine Befragung,keine Befragung,330 *,keine Angaben
1,2,1200001,Fakultät für Chemie und Pharmazie an der Uni Freiburg,Freiburg,Albertstr. 21,79104,90,<NA>,Nur Master SG,keine Angaben,"53,7 %",7.847936,47.998253,NaN,NaN,NaN,Unterstützung im Studium,NaN,Studienorganisation,NaN,Laborpraktika,Angebote zur Berufsorientierung,NaN,Räume,NaN,IT-Infrastruktur,NaN,Weitere Studiengänge am Fachbereich,NaN,NaN
2,2,420102,Fakultät für Biologie an der Uni Freiburg,Freiburg,Schänzlestraße 1,79104,1260,<NA>,11/14 Punkten,"88,2 %","54,9 %",7.847936,47.998253,NaN,NaN,NaN,"2,4",Ranggruppe nicht eindeutig zuweisbar,"2,5","1,6 *","2,4","2,1",Ranggruppe nicht eindeutig zuweisbar,"2,4","1,7","1,8 *","2,3 *","2,2",263,"Abschlüsse: Zwei-Fach-Bachelor, Master of Education; Lehramtstypen: LA Sek II/Gym"
3,2,600799,Wirtschafts- und Verhaltenswissenschaftliche Fakultät an der Uni Freiburg,Freiburg,Platz der Alten Synagoge,79098,530,160,keine Angaben,"83,1 % *","43,5 % *",7.847936,47.998253,NaN,NaN,keine Angabe,NaN,Lehrangebot,NaN,Prüfungen,NaN,Angebote zur Berufsorientierung,NaN,Räume,NaN,IT-Infrastruktur,NaN,Betreuung durch Lehrende,NaN,NaN
4,2,200001,Fakultät für Chemie und Pharmazie an der Uni Freiburg,Freiburg,Albertstr. 21,79104,940,<NA>,7/14 Punkten,"78,9 %",NaN,7.847936,47.998253,NaN,NaN,NaN,NaN,Fallzahl kleiner 15,NaN,Fallzahl kleiner 15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"2,5",NaN,NaN

In [16]:

def clean_sup(x):
    try:
        x = x.split(' ')[0]
        x = (float(x.split('/')[0]))/float((x.split('/')[1]))
        return x
    except:
        return np.nan
    
fbs['support_start'] = fbs['support_start'].apply(lambda x: clean_sup(str(x)))
fbs['support_start'].unique()

array([       nan, 0.78571429, 0.5       , 0.71428571, 0.64285714,
       0.66666667, 0.84615385, 0.28571429, 0.85714286, 0.92857143,
       0.42857143, 0.35714286, 0.75      , 0.83333333, 0.57142857,
       0.58333333, 0.41666667, 1.        , 0.92307692, 0.25      ,
       0.53846154, 0.76923077, 0.46153846, 0.91666667, 0.61538462,
       0.33333333, 0.38461538, 0.69230769, 0.21428571])

In [17]:
clean_sup('12/14 asd')

0.8571428571428571

In [18]:
fbs['tframe_grad_ba'].unique()

array(['73,3 % *', 'keine Angaben', '88,2 %', '83,1 % *', '78,9 %',
       '98,7 %', '73,9 %', '95,3 %', '83,8 %', '54,5 %', nan, '89,4 %',
       '89,5 % *', '92,3 % *', '56,9 %', '92,4 %', '79,7 % *', '79,3 %',
       '81,5 % *', '94,3 %', '49,4 % *', '96,1 % *', '70,1 %', '97,7 %',
       '92,2 %', '57,6 %', '78,5 %', '<10 Absolventen / Jahr', '62,1 %',
       '69,0 %', '36,0 %', '72,6 %', '85,4 % *', '81,8 %', '82,3 %',
       '83,0 %', '89,3 %',
       'nicht durchgängig 10 Absolventen/Jahr im Beobachtungszeitraum; Quelle: Fachbereichsbefragung',
       '88,4 %', '69,0 % *', '89,0 % *', '77,5 % *', '76,8 % *', '95,1 %',
       '91,5 %', '93,6 %',
       'nicht ausgewiesen da weniger 10 Absolventen/Jahr. Quelle: Statistisches Bundesamt',
       '68,0 % *', '73,6 %', '60,0 %', '58,7 %', '79,1 %', '78,7 %',
       '68,5 %', '53,4 %',
       'im Beobachtungszeitraum noch keine Absolventen', '76,2 % *',
       '79,6 %', '92,7 %', '88,1 %', '68,8 %', 'noch keine Absolventen',
       '69,2 %', '86,9 %', '89,1 %', '97,3 %', '84,9 %', '54,4 %',
       '79,1 % *', '80,1 %', '97,7 % *', '71,4 %', '83,2 %', '93,4 %',
       '84,0 %', '90,4 % *', '93,3 % *', '64,6 % *', '80,3 % *', '78,1 %',
       '72,8 %', '74,1 %', '72,1 %', '39,0 %', '47,5 %', '75,0 %',
       '85,3 %', '66,3 % *', '76,5 % *', '65,9 %', '57,4 % *', '98,9 % *',
       '95,3 % *', '70,7 %',
       'noch keine Absolventen im Beobachtungszeitraum; Quelle: Fachbereichsbefragung',
       '86,5 %', '87,6 %', '67,0 %', '70,6 %', '51,1 %', '92,8 % *',
       '84,8 %', '67,5 %', '79,8 %', '96,9 %', '55,8 % *', '98,3 % *',
       '86,1 %', '84,7 %', '48,1 %', '61,4 %', '90,6 % *', '65,6 % *',
       '84,9 % *', '68,2 % *', '95,9 % *', 'kein Bachelorangebot',
       '96,2 % *', '54,1 % *', '64,0 %', '75,8 %', '86,0 %', '36,4 % *',
       '72,4 %', 'nicht gerankt, da weniger als 10 Absolventen/Jahr',
       '100,0 % *', '87,8 % *', '90,2 % *', '35,3 %', '86,7 %', '85,2 %',
       '94,4 %', '92,5 % *', '63,8 %', '74,4 %', '64,2 %', '77,4 % *',
       '83,7 %', '80,6 %', '94,9 %', '78,6 %', '60,5 %', '72,7 %',
       'kein entsprechender Bachelorstudiengang', '97,9 %',
       'nicht ausgewiesen, da weniger als 10 Absolventen/Jahr',
       '80,1 % *', '73,7 % *', '72,0 %', '87,5 %', '93,0 % *', '90,5 % *',
       '91,1 %', '94,8 %', '72,1 % *', '80,2 %', '81,0 % *', '51,3 %',
       '71,6 %', '89,9 % *', '91,7 %', '82,2 %', '93,3 %', '96,8 %',
       '65,4 % *', '81,4 % *', '94,9 % *', '85,7 %', '97,9 % *',
       '80,5 % *', '87,9 %', '90,8 % *', '50,5 % *', '77,8 % *',
       '84,5 % *', '65,0 %', '88,9 % *', '93,5 %', '93,2 %', '96,0 % *',
       '94,3 % *', '88,4 % *', '100,0 %', '93,8 %', '84,2 % *',
       '55,0 % *', '96,3 % *', '78,4 % *', '76,9 % *', '99,7 % *',
       'nicht errechnet, da weniger als 10 Absolventen. Quelle: Statistisches Bundesamt',
       '76,0 %', '68,6 %', '84,6 %', 'keine Daten verfügbar', '98,0 %',
       '81,6 %', '71,9 % *', '95,2 %', '91,9 % *', '67,2 %', '91,7 % *',
       '82,4 %', '96,0 %', '95,1 % *', '96,5 % *', '91,2 % *', '73,6 % *',
       '88,0 % *', '62,7 % *', '88,1 % *', '73,5 %', '91,1 % *', '87,2 %',
       '73,8 %', '82,7 % *', '92,3 %', '84,6 % *', '88,6 % *', '92,0 % *',
       '92,1 % *', '59,8 %', '70,4 %', '82,0 % *', '72,2 %', '54,0 %',
       '38,3 %', '62,5 %', '33,7 %', '49,0 %', '84,5 %', '69,5 %',
       '74,5 %', '71,2 % *', '65,2 %', '84,8 % *', '60,7 % *', '46,7 %',
       '49,2 % *', '47,8 %', '26,2 %', '51,9 % *', '52,3 % *', '70,7 % *',
       '53,3 % *', '66,4 % *', '63,9 %', '50,0 %', '62,4 %', '71,7 %',
       '44,2 %', '59,7 %', '70,9 %', '65,1 %', '66,7 % *', '54,1 %',
       '84,7 % *', '39,4 % *', '32,6 % *', '77,3 % *', '32,1 % *',
       '61,3 %', '70,9 % *', '58,4 %', '77,8 %', '50,0 % *', '46,2 %',
       '73,1 %', '87,7 %', '45,2 %', '64,3 % *', '27,0 % *', '78,8 %',
       '77,7 %', '74,0 % *', 'kein Bachelorstudiengang', '67,6 %',
       '68,4 %', '52,7 %',
       'nicht gerankt, da Studienangebot in Umstrukturierung', '73,2 % *',
       '62,5 % *', '80,0 % *', '75,9 % *', '85,0 % *', '72,4 % *',
       '90,9 % *', '63,8 % *', '72,7 % *', '86,6 % *', '66,7 %',
       '62,1 % *', '75,0 % *', '54,5 % *', '48,0 % *', '78,7 % *',
       '61,7 % *', '71,8 % *', '87,2 % *', '63,4 %', '63,3 %', '65,8 % *',
       '76,6 %', '81,0 %', '83,4 %', '39,2 %', '34,3 %', '50,7 %',
       '43,2 %', '58,5 %', '38,5 %', '86,2 %', '59,4 % *', '60,5 % *',
       '65,2 % *', '91,9 %', '73,3 %', '40,0 %', '61,9 % *', '34,8 % *',
       '87,1 % *', '51,7 %', '56,0 % *', '52,4 %', '86,0 % *', '68,4 % *',
       '82,9 %', '98,4 %', '80,0 %', '82,9 % *', '55,8 %', '89,2 % *',
       '66,2 % *', '85,6 %', '79,5 %', '73,5 % *', '81,8 % *', '76,0 % *',
       '77,9 % *', '56,3 %', '53,6 %', '70,1 % *', '93,1 %', '68,8 % *',
       '85,2 % *', '90,2 %', '84,3 %', '33,3 % *', '85,9 % *', '95,0 % *',
       '92,9 % *', '90,0 % *', '89,7 %', '92,6 %', '86,2 % *', '93,9 % *',
       '80,3 %', '21,8 %', '73,7 %', '82,6 %', '44,0 %', '47,2 %',
       '68,3 %', '65,3 %', '53,5 % *', '44,7 % *', '38,2 % *', '60,6 %',
       '65,0 % *', '36,0 % *', '76,1 %', '67,9 %', '80,9 % *', '85,0 %',
       '79,2 %', '80,2 % *', '70,2 %', '67,7 %', '63,0 %', '37,5 %',
       'wegen Umstrukturierung nicht vergleichbar', '69,6 % *',
       '74,2 % *', '75,8 % *', '94,2 %', '79,7 %', '46,4 % *', '69,2 % *',
       '77,3 %', '61,2 %', '28,1 % *', '34,0 %', '74,0 %', '66,2 %',
       '79,2 % *', '56,1 %', '42,9 %', '82,0 %', '58,5 % *', '44,4 % *',
       '56,5 % *', '80,8 % *', '52,6 % *', '83,0 % *', '69,1 %', '83,3 %',
       '89,6 % *', '73,2 %', '63,7 %', '65,3 % *', '84,1 % *', '89,5 %',
       '78,5 % *', '60,3 %', '78,3 %', '97,1 % *', '95,9 %', '64,7 % *',
       '60,8 % *', '78,0 % *', '59,1 % *', '87,8 %', '81,9 %', '81,3 % *',
       '69,6 %', '68,0 %', '77,5 %', '80,4 %', '86,5 % *', '66,0 %',
       '90,4 %', '90,3 %', '59,3 %', '60,2 %', '76,3 %', '67,1 %',
       '91,3 % *', '68,7 %', '52,3 %', '59,6 %', '59,1 %', '74,3 % *',
       '69,4 % *', '85,6 % *', '73,0 %', '69,7 %', '70,8 % *', '52,8 %',
       '88,8 % *', '64,3 %', '83,5 % *', '94,5 %', '73,9 % *', '45,3 %',
       '71,7 % *', '41,0 %', '57,3 %', '77,6 %', '42,3 % *', '72,8 % *',
       '87,4 %', '68,9 %', '61,0 %', '55,4 %', '62,2 %', '48,5 %',
       '64,2 % *', '86,4 % *', '93,1 % *', '87,9 % *', '58,3 % *',
       '48,6 % *', '51,6 % *', '48,7 % *', '88,7 % *', '63,3 % *',
       '74,6 % *', '61,4 % *', '60,2 % *', '85,7 % *', '96,3 %',
       '90,3 % *', '82,6 % *', '81,2 %', '94,2 % *', '85,8 %', '67,4 % *',
       '84,0 % *', '94,6 % *', '41,4 % *', '53,1 %', '72,9 %', '33,9 % *',
       '44,3 %', '75,6 %', '64,5 % *', '51,0 % *', '59,9 %', '64,7 %',
       '27,7 %', '76,4 %', '55,0 %', '50,4 %', '90,7 % *', '46,7 % *',
       '79,9 % *', '61,1 %', '58,8 % *', '71,6 % *', '98,0 % *', '57,1 %',
       '81,7 %', '63,6 % *', '55,6 %', '46,9 %', '85,4 %', '63,6 %',
       '55,6 % *',
       'Studiengang "Sprach-, Literatur- und Kulturwissenschaften", Auswertung nach Teilfach nicht möglich',
       '95,2 % *', '83,9 %', '61,6 %', '48,6 %', '89,8 %', '76,7 %',
       '84,4 %', '75,1 % *', '57,1 % *', '45,0 % *', '84,4 % *', '90,1 %',
       '87,5 % *', '61,2 % *', '92,2 % *', '97,8 %', '71,3 % *',
       '79,5 % *', '63,1 %', '62,4 % *', '97,2 %', '78,3 % *', '78,0 %',
       '88,5 %', '42,5 % *', '77,9 %', '33,3 %', '83,9 % *', '86,8 % *',
       '75,4 %',
       'nicht gerankt da im im Durchschnitt <10 Absolventen/Jahr',
       '53,8 % *', '85,8 % *', '79,3 % *', '55,2 %', '83,8 % *', '86,4 %',
       '43,6 %', '67,9 % *', '58,6 % *', '89,7 % *', '46,8 % *', '92,5 %',
       '70,8 %', '90,8 %', '89,2 %', '88,9 %', '85,5 %', '91,0 %',
       '93,5 % *', '85,9 %', '72,9 % *', '32,3 % *', '24,2 %', '39,4 %',
       '61,1 % *', '87,3 %', '55,5 % *', '35,1 % *', '70,0 %', '63,9 % *',
       '91,8 %', '72,2 % *', '49,2 %', '30,3 %', '87,6 % *', '62,6 %',
       '52,4 % *', '36,5 % *', '78,2 %', '60,3 % *', '38,7 % *',
       '77,6 % *', '74,6 %', '43,1 %', '59,2 % *', '77,1 %', '30,8 %',
       'Studienangebot erst ab WS 2018/19', '91,3 %', '53,2 % *',
       '35,5 % *', '29,3 % *', '52,5 % *', '60,9 %', '90,9 %', '88,8 %',
       '22,7 %', '41,5 % *', '95,7 % *', '99,3 %', '87,4 % *', '68,1 %',
       '98,3 %', '59,6 % *', '92,0 %', '72,0 % *', '94,0 % *', '58,2 %',
       '40,0 % *', '86,7 % *', '83,4 % *', '71,1 % *', '75,2 % *',
       '48,8 % *', '71,5 %', '63,1 % *', '81,4 %', '10,0 % *', '83,2 % *',
       '65,1 % *', '93,0 %', '83,7 % *', '72,3 %', '72,5 %', '67,2 % *',
       '63,0 % *', '69,1 % *', '98,6 % *', '98,5 % *', '90,7 %',
       '79,8 % *', '94,4 % *', '78,4 %', '37,5 % *', '76,3 % *',
       '45,8 % *', '52,0 % *', '68,7 % *', '96,7 % *', '59,3 % *',
       '50,1 % *', '56,8 % *', '51,3 % *', '58,7 % *', '66,5 %',
       '61,8 % *', '83,6 % *', '62,3 % *', '75,9 %',
       'keine Daten Verfügbar', '30,6 % *', '64,1 % *', '68,3 % *',
       '71,4 % *', '81,2 % *', '82,2 % *', '81,7 % *', '86,3 % *',
       '69,8 % *', '95,6 % *', '68,1 % *', '82,4 % *', '62,2 % *',
       '41,9 % *', '55,9 % *', '90,0 %', '61,7 %',
       'nicht ausgewiesen, da weniger als 10 Absolventen/Jahr; Quelle: Statistisches Bundesamt',
       '45,7 % *', '34,0 % *', '43,8 %', '31,4 %', '52,9 %', '61,5 % *',
       '43,4 % *', '58,6 %', '62,6 % *', '31,0 % *', '70,5 % *',
       '<10 Absolventen / Jahr; Quelle: Statistisches Bundesamt',
       '41,7 % *', '64,9 % *', '52,1 %',
       'nicht gerankt, da ausschließlich berufsbegleitendes Studienangebot',
       '92,1 %', '67,6 % *', '21,8 % *', '43,2 % *', '70,0 % *',
       '42,9 % *', '37,1 % *', '52,9 % *', '58,2 % *', '67,8 %', '95,5 %',
       '89,4 % *', '57,7 %', '69,4 %', '71,0 % *', '74,5 % *', '54,3 % *',
       '51,8 %', '37,3 % *', '28,4 % *', '43,5 % *', '27,6 % *', '26,5 %',
       '35,1 %', '41,5 %', '63,5 % *', '41,2 % *', '49,1 %', '65,9 % *',
       '76,6 % *', '39,0 % *', '58,0 % *', '59,8 % *', '57,7 % *',
       '28,6 % *', '40,4 % *', '97,5 %', '71,2 %', '63,2 % *', '96,1 %',
       '51,2 % *', '46,8 %', '80,7 % *', '79,6 % *', '91,8 % *',
       '75,7 % *', '36,7 %', '64,8 % *', '16,0 % *', '20,0 % *',
       '78,6 % *', '53,1 % *', '60,4 % *', '75,7 %', '67,0 % *',
       '69,7 % *', '41,0 % *', '95,8 % *', '64,6 %', '87,7 % *',
       'nicht ausgewiesen, da ausschließlich berufsbegleitendes Studienangebot',
       '70,6 % *',
       'ausschließlich duales Studienangebot, Indikator wird nicht berechnet',
       '98,7 % *', '99,3 % *', '95,0 %', '91,4 % *',
       'nicht gerankt, da ausschließlich Lehramtstudiengänge', '91,0 % *',
       '97,4 %', '88,0 %'], dtype=object)

In [19]:
def clean_sup(x):
    try:
        x = x.split(' ')[0]
        x = float(x.replace(',','.'))/100
        return x
    except:
        return np.nan
    
fbs['tframe_grad_ba'] = fbs['tframe_grad_ba'].apply(lambda x: clean_sup(str(x)))
fbs['tframe_grad_ba'].unique()

array([0.733,   nan, 0.882, 0.831, 0.789, 0.987, 0.739, 0.953, 0.838,
       0.545, 0.894, 0.895, 0.923, 0.569, 0.924, 0.797, 0.793, 0.815,
       0.943, 0.494, 0.961, 0.701, 0.977, 0.922, 0.576, 0.785, 0.621,
       0.69 , 0.36 , 0.726, 0.854, 0.818, 0.823, 0.83 , 0.893, 0.884,
       0.89 , 0.775, 0.768, 0.951, 0.915, 0.936, 0.68 , 0.736, 0.6  ,
       0.587, 0.791, 0.787, 0.685, 0.534, 0.762, 0.796, 0.927, 0.881,
       0.688, 0.692, 0.869, 0.891, 0.973, 0.849, 0.544, 0.801, 0.714,
       0.832, 0.934, 0.84 , 0.904, 0.933, 0.646, 0.803, 0.781, 0.728,
       0.741, 0.721, 0.39 , 0.475, 0.75 , 0.853, 0.663, 0.765, 0.659,
       0.574, 0.989, 0.707, 0.865, 0.876, 0.67 , 0.706, 0.511, 0.928,
       0.848, 0.675, 0.798, 0.969, 0.558, 0.983, 0.861, 0.847, 0.481,
       0.614, 0.906, 0.656, 0.682, 0.959, 0.962, 0.541, 0.64 , 0.758,
       0.86 , 0.364, 0.724, 1.   , 0.878, 0.902, 0.353, 0.867, 0.852,
       0.944, 0.925, 0.638, 0.744, 0.642, 0.774, 0.837, 0.806, 0.949,
       0.786, 0.605, 0.727, 0.979, 0.737, 0.72 , 0.875, 0.93 , 0.905,
       0.911, 0.948, 0.802, 0.81 , 0.513, 0.716, 0.899, 0.917, 0.822,
       0.968, 0.654, 0.814, 0.857, 0.805, 0.879, 0.908, 0.505, 0.778,
       0.845, 0.65 , 0.889, 0.935, 0.932, 0.96 , 0.938, 0.842, 0.55 ,
       0.963, 0.784, 0.769, 0.997, 0.76 , 0.686, 0.846, 0.98 , 0.816,
       0.719, 0.952, 0.919, 0.672, 0.824, 0.965, 0.912, 0.88 , 0.627,
       0.735, 0.872, 0.738, 0.827, 0.886, 0.92 , 0.921, 0.598, 0.704,
       0.82 , 0.722, 0.54 , 0.383, 0.625, 0.337, 0.49 , 0.695, 0.745,
       0.712, 0.652, 0.607, 0.467, 0.492, 0.478, 0.262, 0.519, 0.523,
       0.533, 0.664, 0.639, 0.5  , 0.624, 0.717, 0.442, 0.597, 0.709,
       0.651, 0.667, 0.394, 0.326, 0.773, 0.321, 0.613, 0.584, 0.462,
       0.731, 0.877, 0.452, 0.643, 0.27 , 0.788, 0.777, 0.74 , 0.676,
       0.684, 0.527, 0.732, 0.8  , 0.759, 0.85 , 0.909, 0.866, 0.48 ,
       0.617, 0.718, 0.634, 0.633, 0.658, 0.766, 0.834, 0.392, 0.343,
       0.507, 0.432, 0.585, 0.385, 0.862, 0.594, 0.4  , 0.619, 0.348,
       0.871, 0.517, 0.56 , 0.524, 0.829, 0.984, 0.892, 0.662, 0.856,
       0.795, 0.779, 0.563, 0.536, 0.931, 0.843, 0.333, 0.859, 0.95 ,
       0.929, 0.9  , 0.897, 0.926, 0.939, 0.218, 0.826, 0.44 , 0.472,
       0.683, 0.653, 0.535, 0.447, 0.382, 0.606, 0.761, 0.679, 0.809,
       0.792, 0.702, 0.677, 0.63 , 0.375, 0.696, 0.742, 0.942, 0.464,
       0.612, 0.281, 0.34 , 0.561, 0.429, 0.444, 0.565, 0.808, 0.526,
       0.691, 0.833, 0.896, 0.637, 0.841, 0.603, 0.783, 0.971, 0.647,
       0.608, 0.78 , 0.591, 0.819, 0.813, 0.804, 0.66 , 0.903, 0.593,
       0.602, 0.763, 0.671, 0.913, 0.687, 0.596, 0.743, 0.694, 0.73 ,
       0.697, 0.708, 0.528, 0.888, 0.835, 0.945, 0.453, 0.41 , 0.573,
       0.776, 0.423, 0.874, 0.689, 0.61 , 0.554, 0.622, 0.485, 0.864,
       0.583, 0.486, 0.516, 0.487, 0.887, 0.746, 0.812, 0.858, 0.674,
       0.946, 0.414, 0.531, 0.729, 0.339, 0.443, 0.756, 0.645, 0.51 ,
       0.599, 0.277, 0.764, 0.504, 0.907, 0.799, 0.611, 0.588, 0.571,
       0.817, 0.636, 0.556, 0.469, 0.839, 0.616, 0.898, 0.767, 0.844,
       0.751, 0.45 , 0.901, 0.978, 0.713, 0.631, 0.972, 0.885, 0.425,
       0.868, 0.754, 0.538, 0.552, 0.436, 0.586, 0.468, 0.855, 0.91 ,
       0.323, 0.242, 0.873, 0.555, 0.351, 0.7  , 0.918, 0.303, 0.626,
       0.365, 0.782, 0.387, 0.431, 0.592, 0.771, 0.308, 0.532, 0.355,
       0.293, 0.525, 0.609, 0.227, 0.415, 0.957, 0.993, 0.681, 0.94 ,
       0.582, 0.711, 0.752, 0.488, 0.715, 0.1  , 0.723, 0.725, 0.986,
       0.985, 0.458, 0.52 , 0.967, 0.501, 0.568, 0.665, 0.618, 0.836,
       0.623, 0.306, 0.641, 0.863, 0.698, 0.956, 0.419, 0.559, 0.457,
       0.438, 0.314, 0.529, 0.615, 0.434, 0.31 , 0.705, 0.417, 0.649,
       0.521, 0.371, 0.678, 0.955, 0.577, 0.71 , 0.543, 0.518, 0.373,
       0.284, 0.435, 0.276, 0.265, 0.635, 0.412, 0.491, 0.58 , 0.286,
       0.404, 0.975, 0.632, 0.512, 0.807, 0.757, 0.367, 0.648, 0.16 ,
       0.2  , 0.604, 0.958, 0.914, 0.974])

In [20]:
def clean_sup(x):
    try:
        x = x.split(' ')[0]
        x = float(x.replace(',','.'))/100
        return x
    except:
        return np.nan
    
fbs['tframe_grad_ma'] = fbs['tframe_grad_ma'].apply(lambda x: clean_sup(str(x)))
fbs['tframe_grad_ma'].unique()

array([0.267, 0.537, 0.549, 0.435,   nan, 0.676, 0.109, 0.32 , 0.136,
       0.213, 0.295, 0.63 , 0.85 , 0.154, 0.237, 0.509, 0.329, 0.153,
       0.548, 0.766, 0.473, 0.402, 0.532, 0.778, 0.759, 0.714, 0.364,
       0.583, 0.651, 0.914, 0.645, 0.67 , 0.677, 0.333, 0.193, 0.207,
       0.299, 0.426, 0.49 , 0.348, 0.861, 0.493, 0.116, 0.597, 0.771,
       0.692, 0.565, 0.882, 0.46 , 0.798, 0.905, 0.788, 0.874, 0.737,
       0.921, 0.681, 0.427, 0.588, 0.526, 0.227, 0.508, 0.388, 0.456,
       0.595, 0.308, 0.667, 0.397, 0.593, 0.898, 0.807, 0.385, 0.206,
       0.352, 0.478, 0.462, 0.414, 0.811, 0.345, 0.833, 0.683, 0.38 ,
       0.551, 0.542, 0.75 , 0.638, 0.649, 1.   , 0.717, 0.29 , 0.313,
       0.494, 0.297, 0.111, 0.511, 0.962, 0.612, 0.465, 0.268, 0.459,
       0.371, 0.429, 0.606, 0.281, 0.786, 0.433, 0.452, 0.381, 0.127,
       0.408, 0.265, 0.4  , 0.594, 0.636, 0.531, 0.937, 0.422, 0.475,
       0.89 , 0.796, 0.34 , 0.838, 0.222, 0.42 , 0.57 , 0.528, 0.907,
       0.904, 0.492, 0.817, 0.848, 0.951, 0.723, 0.421, 0.554, 0.521,
       0.81 , 0.885, 0.912, 0.781, 0.72 , 0.722, 0.947, 0.846, 0.963,
       0.468, 0.711, 0.789, 0.893, 0.35 , 0.728, 0.8  , 0.797, 0.424,
       0.702, 0.757, 0.485, 0.444, 0.471, 0.552, 0.373, 0.525, 0.5  ,
       0.241, 0.724, 0.118, 0.56 , 0.865, 0.538, 0.675, 0.183, 0.454,
       0.229, 0.284, 0.405, 0.37 , 0.298, 0.353, 0.412, 0.913, 0.176,
       0.393, 0.368, 0.235, 0.19 , 0.324, 0.301, 0.453, 0.163, 0.641,
       0.6  , 0.479, 0.763, 0.432, 0.484, 0.2  , 0.25 , 0.663, 0.271,
       0.263, 0.217, 0.506, 0.231, 0.375, 0.258, 0.808, 0.504, 0.547,
       0.379, 0.688, 0.275, 0.23 , 0.708, 0.571, 0.316, 0.464, 0.55 ,
       0.417, 0.439, 0.305, 0.423, 0.481, 0.167, 0.31 , 0.634, 0.653,
       0.901, 0.449, 0.411, 0.769, 0.347, 0.303, 0.556, 0.205, 0.603,
       0.174, 0.519, 0.639, 0.545, 0.59 , 0.806, 0.   , 0.103, 0.65 ,
       0.367, 0.45 , 0.599, 0.189, 0.357, 0.746, 0.812, 0.384, 0.383,
       0.804, 0.425, 0.578, 0.776, 0.406, 0.446, 0.587, 0.524, 0.577,
       0.318, 0.881, 0.574, 0.431, 0.507, 0.41 , 0.24 , 0.105, 0.864,
       0.816, 0.875, 0.831, 0.889, 0.935, 0.9  , 0.436, 0.561, 0.328,
       0.365, 0.394, 0.732, 0.642, 0.738, 0.349, 0.618, 0.619, 0.288,
       0.407, 0.354, 0.455, 0.64 , 0.837, 0.646, 0.286, 0.949, 0.802,
       0.933, 0.358, 0.879, 0.182, 0.748, 0.727, 0.169, 0.617, 0.404,
       0.633, 0.434, 0.172, 0.849, 0.62 , 0.342, 0.544, 0.261, 0.546,
       0.355, 0.736, 0.679, 0.877, 0.923, 0.86 , 0.188, 0.441, 0.327,
       0.909, 0.443, 0.148, 0.744, 0.656, 0.209, 0.659, 0.273, 0.671,
       0.178, 0.77 , 0.251, 0.644, 0.415, 0.369, 0.403, 0.535, 0.707,
       0.632, 0.294, 0.611, 0.689, 0.262, 0.469, 0.621, 0.214, 0.451,
       0.625, 0.259, 0.08 , 0.304, 0.413, 0.36 , 0.306, 0.461, 0.83 ,
       0.631, 0.539, 0.564, 0.514, 0.758, 0.517, 0.862, 0.627, 0.359,
       0.247, 0.512, 0.192, 0.53 , 0.68 , 0.157, 0.596, 0.246, 0.745,
       0.39 , 0.7  , 0.853, 0.992, 0.981, 0.445, 0.296, 0.392, 0.706,
       0.419, 0.325, 0.774, 0.783, 0.592, 0.476, 0.709, 0.22 , 0.615,
       0.558, 0.761, 0.106, 0.249, 0.219, 0.212, 0.255, 0.289, 0.463,
       0.28 , 0.536, 0.326, 0.279, 0.543, 0.568, 0.884, 0.824, 0.84 ,
       0.541, 0.391, 0.533, 0.784, 0.585, 0.725, 0.17 , 0.752, 0.735,
       0.487, 0.665, 0.946, 0.495, 0.859, 0.457, 0.818, 0.181, 0.703,
       0.133, 0.586, 0.58 , 0.698, 0.438, 0.966, 0.61 , 0.95 , 0.976,
       0.941, 0.88 , 0.953, 0.969, 0.813, 0.952, 0.428, 0.829, 0.985,
       0.283, 0.821, 0.857, 0.842, 0.827, 0.916, 0.825, 0.926, 0.712,
       0.876, 0.938, 0.987, 0.964, 0.906, 0.984, 0.762, 0.955, 0.523,
       0.658, 0.729, 0.696, 0.896, 0.844, 0.344, 0.902, 0.801, 0.726,
       0.474, 0.44 , 0.855, 0.863, 0.94 , 0.488, 0.779, 0.07 , 0.482,
       0.693, 0.377, 0.917, 0.143, 0.48 , 0.607, 0.888, 0.974, 0.852,
       0.871, 0.389, 0.66 , 0.765, 0.91 , 0.958, 0.576, 0.69 , 0.081,
       0.814, 0.165, 0.314, 0.311, 0.939, 0.733, 0.892, 0.575, 0.396,
       0.609, 0.919, 0.872, 0.643, 0.749, 0.99 , 0.346, 0.979, 0.92 ,
       0.591, 0.573, 0.486])

In [21]:
fbs['int_ba'].unique()

array(['Indikator nicht ausgewiesen', nan, '3/9 Punkten', '2/9 Punkten',
       '5/9 Punkten', '4/13 Punkten', '4/10 Punkten', '4/9 Punkten',
       '3/10 Punkten', '1/9 Punkten', '6/9 Punkten', '7/13 Punkten',
       '6/13 Punkten', '8/9 Punkten', '8/13 Punkten', '7/9 Punkten',
       'kein entsprechender Bachelorstudiengang', '5/13 Punkten',
       '5/10 Punkten', 'Internationale Ausrichtung, Master',
       '9/13 Punkten', '2/10 Punkten', '8/10 Punkten', '3/13 Punkten',
       'kein Bachelorstudiengang', '6/10 Punkten', '10/13 Punkten',
       '2/13 Punkten', '7/10 Punkten', '8/12 Punkten', '3/12 Punkten',
       '7/12 Punkten', '6/12 Punkten', '9/12 Punkten', '5/12 Punkten',
       '10/12 Punkten', '1/10 Punkten', '4/12 Punkten', '1/13 Punkten',
       '0/10 Punkten'], dtype=object)

In [22]:
def clean_sup(x):
    try:
        x = x.split(' ')[0]
        x = (float(x.split('/')[0]))/float((x.split('/')[1]))
        return x
    except:
        return np.nan
fbs['int_ba'] = fbs['int_ba'].apply(lambda x: clean_sup(str(x)))
fbs['int_ba'].unique()

array([       nan, 0.33333333, 0.22222222, 0.55555556, 0.30769231,
       0.4       , 0.44444444, 0.3       , 0.11111111, 0.66666667,
       0.53846154, 0.46153846, 0.88888889, 0.61538462, 0.77777778,
       0.38461538, 0.5       , 0.69230769, 0.2       , 0.8       ,
       0.23076923, 0.6       , 0.76923077, 0.15384615, 0.7       ,
       0.25      , 0.58333333, 0.75      , 0.41666667, 0.83333333,
       0.1       , 0.07692308, 0.        ])

In [23]:
def clean_sup(x):
    try:
        x = x.split(' ')[0]
        x = (float(x.split('/')[0]))/float((x.split('/')[1]))
        return x
    except:
        return np.nan
fbs['int_ma'] = fbs['int_ma'].apply(lambda x: clean_sup(str(x)))
fbs['int_ma'].unique()

array([       nan, 0.44444444, 0.66666667, 0.55555556, 0.22222222,
       0.46153846, 0.9       , 0.33333333, 0.30769231, 0.53846154,
       0.4       , 0.77777778, 0.11111111, 0.88888889, 0.61538462,
       0.38461538, 0.6       , 0.69230769, 0.76923077, 0.3       ,
       0.23076923, 0.5       , 0.84615385, 0.92307692, 1.        ,
       0.2       , 0.8       , 0.25      , 0.16666667, 0.75      ,
       0.58333333, 0.41666667, 0.83333333, 0.7       , 0.91666667,
       0.07692308, 0.        , 0.1       , 0.15384615])

In [24]:
def clean_sup(x):
    try:
        x = x.split(' ')[0]
        x = float(x.replace(',','.'))/100
        return x
    except:
        return np.nan
fbs['foreign_spot'] = fbs['foreign_spot'].apply(lambda x: clean_sup(str(x)))
fbs['foreign_spot'].unique()

array([ nan, 0.02, 0.07, 0.04, 0.03, 0.18, 0.01, 0.14, 0.17, 0.2 , 0.33,
       0.32, 0.06, 0.05, 0.  , 0.23, 0.25, 0.1 , 0.12, 0.09, 0.16, 0.08,
       1.  , 0.29, 0.26, 0.11, 0.13, 0.27, 0.41, 0.19, 0.68, 0.15])

In [25]:

def clean_sup(x):
    try:
        x = x.split(' ')[0]
        x = float(x.replace(',','.'))
        return x
    except:
        return np.nan
fbs['sup_doz'] = fbs['sup_doz'].apply(lambda x: clean_sup(str(x)))
fbs['sup_doz'].unique()

array([nan, 2.4, 2.5, 2.2, 2.7, 1.5, 2.1, 1.9, 2.9, 2.3, 2. , 3.3, 1.6,
       1.8, 1.7, 2.6, 3.2, 3.1, 1.4, 3.6, 2.8, 3. , 1.2, 1.3, 3.5])

In [26]:
for zahl in ['sup_in_studies','curriculum',	'students_orga',	'exams',	'research_conn',	'offer_joborientation',	'supp_exchange',	'faculties',	'bib',	'it_infrastructure',	'grade_overall']:

    fbs[zahl] = fbs[zahl].apply(lambda x: clean_sup(str(x)))

In [27]:
fbs.head()

,id_uni,id_fak,name_fb,city,street_nr,plz,total_stud,total_stud_ma,support_start,tframe_grad_ba,tframe_grad_ma,lon,lat,int_ba,int_ma,foreign_spot,sup_doz,sup_in_studies,curriculum,students_orga,exams,research_conn,offer_joborientation,supp_exchange,faculties,bib,it_infrastructure,grade_overall,total_students_la,la_studies
0,2,30546,Philologische Fakultät an der Uni Freiburg,Freiburg,Rempartstraße 15,79085,470,130,NaN,0.733,0.267,7.847936,47.998253,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,330 *,keine Angaben
1,2,1200001,Fakultät für Chemie und Pharmazie an der Uni Freiburg,Freiburg,Albertstr. 21,79104,90,<NA>,NaN,NaN,0.537,7.847936,47.998253,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,420102,Fakultät für Biologie an der Uni Freiburg,Freiburg,Schänzlestraße 1,79104,1260,<NA>,0.785714,0.882,0.549,7.847936,47.998253,NaN,NaN,NaN,2.4,NaN,2.5,1.6,2.4,2.1,NaN,2.4,1.7,1.8,2.3,2.2,263,"Abschlüsse: Zwei-Fach-Bachelor, Master of Education; Lehramtstypen: LA Sek II/Gym"
3,2,600799,Wirtschafts- und Verhaltenswissenschaftliche Fakultät an der Uni Freiburg,Freiburg,Platz der Alten Synagoge,79098,530,160,NaN,0.831,0.435,7.847936,47.998253,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2,200001,Fakultät für Chemie und Pharmazie an der Uni Freiburg,Freiburg,Albertstr. 21,79104,940,<NA>,0.500000,0.789,NaN,7.847936,47.998253,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.5,NaN,NaN

In [28]:
def clean_sup(x):
    try:
        x = str(x).replace(' *','').replace('.','')
        x = int(x)
        return x
    except:
        return np.nan

fbs['total_students_la'] = fbs['total_students_la'].apply(lambda x: clean_sup(str(x)))


fbs['total_students_la'].unique()

array([ 330.,   nan,  263.,  214.,  610.,  224.,  191.,  910.,  216.,
        331.,  940.,  338.,  284.,   69.,  150.,  105.,  101.,  520.,
        151.,  460.,  240.,  340.,  320.,  540.,  500.,  303.,  960.,
        326.,  313., 1010.,  159., 8320., 2931.,  480.,  267.,  760.,
        100.,  256.,  234.,  170.,  288.,  155.,  190.,  370.,   35.,
        450.,  699.,  317.,  920.,  964., 1440.,  271.,  182.,  950.,
        653., 1130., 2462., 1050.,  427., 1120.,  687.,  690., 1220.,
        430.,  186.,  253.,  623.,  580.,  474.,  800.,  433.,  277.,
        169., 1420., 1034.,   10.,  158.,  300.,  680.,  443.,  810.,
        761., 1030.,  842., 2690., 1869.,  758.,  980.,  192.,  207.,
       1100.,   95.,  125.,  470.,   66.,  290.,  416.,  440.,  348.,
        650., 1300.,   49.,  160.,  239.,  193.,  180.,  336.,  394.,
        720., 1032.,  257.,  154.,  951.,  230.,  362.,  360., 1256.,
        700.,  130.,  799., 2700., 1198.,  247.,  426.,  640.,  728.,
        422.,  250., 1460., 3022., 4390., 1181., 3960., 3445., 1854.,
        174.,   86., 1560.,  750., 1800.,  518.,   36.,  410.,  120.,
        172.,  647.,  830.,  489.,  530.,  412.,  200.,  459.,  135.,
        642.,  757., 1640.,  691.,  378.,  752.,  406.,  270.,  730.,
       2060., 1107., 2910., 2330., 1098., 1280., 1580., 2279., 1210.,
       1860., 1691.,  630.])

In [29]:
fbs['la_studies'].nunique()

102

In [30]:
fbs.drop('la_studies', axis = 1, inplace = True)

In [31]:
fbs.to_csv('./data/fbs_cleaned.csv')

In [36]:
fbs.columns

Index(['id_uni', 'id_fak', 'name_fb', 'city', 'street_nr', 'plz', 'total_stud',
       'total_stud_ma', 'support_start', 'tframe_grad_ba', 'tframe_grad_ma',
       'lon', 'lat', 'int_ba', 'int_ma', 'foreign_spot', 'sup_doz',
       'sup_in_studies', 'curriculum', 'students_orga', 'exams',
       'research_conn', 'offer_joborientation', 'supp_exchange', 'faculties',
       'bib', 'it_infrastructure', 'grade_overall', 'total_students_la'],
      dtype='object')

In [38]:
rel_ba = (fbs['total_stud'].mean()-fbs['total_stud_ma'].mean())/(fbs['total_stud'].mean())
rel_ma = 1 - rel_ba
print(rel_ba)
print(rel_ma)

0.7731790219665312
0.2268209780334688

In [49]:
fbs['total_stud'].isnull().value_counts()
#fbs['total_stud'].count()

False    1724
True     527
Name: total_stud, dtype: int64

In [75]:
def definer_mg(x):
    x = x.lower() 
    if  x.find('medi') > -1 or x.find('medi') > -1 or x.find('gesund') > -1 or x.find('pharma') > -1 or x.find('spo') > -1 or x.find('psy') > -1  or x.find('lebe') > -1 or x.find('human') > -1 or x.find('leben') > -1:
        return 1
    else:
        return 0
def definer_mn(x):
    x = x.lower() 
    if x.find('math') > -1 or x.find('phy') > -1 or x.find('tech') > -1 or x.find('chem') > -1 or x.find('bio') > -1 or x.find('mint') > -1 or x.find('nat') > -1 or x.find('geo') > -1:
        return 1
    else:
        return 0
def definer_rws(x): 
    x = x.lower() 
    if x.find('wirt') > -1 or x.find('sozial') > -1 or x.find('recht') > -1  or x.find('jur') > -1  or x.find('betr') > -1 or x.find('gese') > -1 or x.find('pol') > -1  or x.find('ver') > -1 or x.find('geist') > -1 or x.find('volksw') > -1 or x.find('bwl') > -1:
        return 1
    else:
        return 0
def definer_sk(x):
    x = x.lower()  
    if x.find('eng') > -1 or x.find('phil') > -1 or x.find('phil') > -1 or x.find('fran') > -1 or x.find('amer') > -1 or x.find('angl') > -1  or x.find('jap') > -1 or x.find('asia') > -1 or x.find('ling') > -1 or x.find('kult') > -1 or x.find('lit') > -1:
        return 1
    else:
        return 0
def definer_ii(x):
    x = x.lower() 
    if x.find('ing') > -1 or x.find('info') > -1 or x.find('tech') > -1 or x.find('masch') > -1 or x.find('elektro') > -1 or x.find('arch') > -1 or x.find('fran') > -1 or x.find('bau') > -1 or x.find('luft') > -1 or x.find('raum') > -1 :
        return 1
    else:
        return 0

In [76]:
fbs['med_d'] = fbs['name_fb'].apply(lambda x: definer_mg(x))
fbs['nat_d'] = fbs['name_fb'].apply(lambda x: definer_mn(x))
fbs['rws_d'] = fbs['name_fb'].apply(lambda x: definer_rws(x))
fbs['spr_d'] = fbs['name_fb'].apply(lambda x: definer_sk(x))
fbs['ing_d'] = fbs['name_fb'].apply(lambda x: definer_ii(x))
fbs.head()

,id_uni,id_fak,name_fb,city,street_nr,plz,total_stud,total_stud_ma,support_start,tframe_grad_ba,tframe_grad_ma,lon,lat,int_ba,int_ma,foreign_spot,sup_doz,sup_in_studies,curriculum,students_orga,exams,research_conn,offer_joborientation,supp_exchange,faculties,bib,it_infrastructure,grade_overall,total_students_la,total_students_ma_appr,med_d,nat_d,rws_d,spr_d,ing_d,sum
0,2,30546,Philologische Fakultät an der Uni Freiburg,Freiburg,Rempartstraße 15,79085,470,130,NaN,0.733,0.267,7.847936,47.998253,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,330.0,340,0,0,0,1,0,0
1,2,1200001,Fakultät für Chemie und Pharmazie an der Uni Freiburg,Freiburg,Albertstr. 21,79104,90,<NA>,NaN,NaN,0.537,7.847936,47.998253,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,1,1,0,1,0,0
2,2,420102,Fakultät für Biologie an der Uni Freiburg,Freiburg,Schänzlestraße 1,79104,1260,<NA>,0.785714,0.882,0.549,7.847936,47.998253,NaN,NaN,NaN,2.4,NaN,2.5,1.6,2.4,2.1,NaN,2.4,1.7,1.8,2.3,2.2,263.0,<NA>,0,1,0,1,0,0
3,2,600799,Wirtschafts- und Verhaltenswissenschaftliche Fakultät an der Uni Freiburg,Freiburg,Platz der Alten Synagoge,79098,530,160,NaN,0.831,0.435,7.847936,47.998253,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,370,0,0,1,1,0,0
4,2,200001,Fakultät für Chemie und Pharmazie an der Uni Freiburg,Freiburg,Albertstr. 21,79104,940,<NA>,0.500000,0.789,NaN,7.847936,47.998253,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.5,NaN,<NA>,1,1,0,1,0,0

In [81]:
fbs['sonst'] = fbs[['med_d','nat_d','rws_d','spr_d','ing_d']].apply(lambda x: 0 if x.med_d + x.nat_d + x.rws_d + x.spr_d + x.ing_d > 0 else 1, axis = 1)
fbs['sonst'].value_counts()
fbs[fbs['sonst']==1]

,id_uni,id_fak,name_fb,city,street_nr,plz,total_stud,total_stud_ma,support_start,tframe_grad_ba,tframe_grad_ma,lon,lat,int_ba,int_ma,foreign_spot,sup_doz,sup_in_studies,curriculum,students_orga,exams,research_conn,offer_joborientation,supp_exchange,faculties,bib,it_infrastructure,grade_overall,total_students_la,total_students_ma_appr,med_d,nat_d,rws_d,spr_d,ing_d,sonst
442,60,30056,Fachbereich 12: Erziehungs- und Bildungswissenschaften an der Uni Bremen,Bremen,Bibliotheksstraße 1-3,28359,140,140,NaN,NaN,0.547,8.853993,53.107938,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,1
579,76,30241,Fachbereich 21: Erziehungswissenschaften an der Uni Marburg,Marburg,Wilhelm-Röpke-Straße 6 B,35032,930,210,NaN,0.779,0.587,8.774128,50.810098,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,720,0,0,0,0,0,1
581,76,30237,Fachbereich 09: Germanistik und Kunstwissenschaften an der Uni Marburg,Marburg,Deutschhausstraße 3,35032,1030,340,0.500000,0.823,NaN,8.774128,50.810098,0.444444,0.333333,0.01,2.2,3.0,NaN,NaN,2.4,2.5,NaN,NaN,NaN,1.9,2.1,NaN,1100.0,690,0,0,0,0,0,1
591,76,430606,Fachbereich 21 Erziehungswissenschaften an der Uni Marburg,Marburg,Barfüßerstraße 1,35032,750,<NA>,NaN,NaN,0.574,8.774128,50.810098,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,0,0,0,0,0,1
944,126,30197,Fachbereich 1: Bildungswissenschaften (Koblenz) an der Uni Kobl.-Land./Koblenz,Koblenz,Universitätsstraße 1,56070,640,120,NaN,0.928,0.737,7.559893,50.364317,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,520,0,0,0,0,0,1
974,132,30620,Fachbereich II an der Uni Trier,Trier,Universitätsring 15,54286,250,50,NaN,0.467,NaN,6.682927,49.745735,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,370.0,200,0,0,0,0,0,1
977,132,30621,Fachbereich I an der Uni Trier,Trier,Universitätsring 15,54286,1000,290,NaN,0.902,0.390,6.682927,49.745735,NaN,NaN,NaN,2.8,NaN,3.6,NaN,3.3,3.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,710,0,0,0,0,0,1
980,132,30297,Fachbereich II an der Uni Trier,Trier,Universitätsring 15,54286,690,60,NaN,0.769,0.700,6.682927,49.745735,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,500.0,630,0,0,0,0,0,1
981,132,400166,Fachbereich IV an der Uni Trier,Trier,Universitätsring 15,54286,260,90,0.571429,NaN,NaN,6.682927,49.745735,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,170,0,0,0,0,0,1
983,132,400168,Fachbereich IV an der Uni Trier,Trier,Universitätsring 15,54286,350,40,NaN,0.750,0.571,6.682927,49.745735,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,310,0,0,0,0,0,1
984,132,604149,Fachbereich I an der Uni Trier,Trier,Universitätsring 15,54286,70,<NA>,NaN,NaN,NaN,6.682927,49.745735,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,0,0,0,0,0,1
985,132,100151,Fachbereich III an der Uni Trier,Trier,Universitätsring 15,54296,1010,<NA>,0.642857,0.611,NaN,6.682927,49.745735,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,0,0,0,0,0,1
986,132,30299,Fachbereich I an der Uni Trier,Trier,Universitätsring 15,54296,1660,500,0.428571,0.865,0.853,6.682927,49.745735,0.111111,0.222222,0.01,2.0,2.4,2.6,2.2,2.6,2.0,3.4,2.5,2.4,NaN,2.1,2.1,NaN,1160,0,0,0,0,0,1
987,132,440062,Fachbereich II an der Uni Trier,Trier,Universitätsring 15,54286,50,10,0.714286,NaN,NaN,6.682927,49.745735,0.666667,0.666667,0.11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40,0,0,0,0,0,1
1236,176,30534,Fachbereich Bildungswissenschaften an der Uni Duisburg-Essen/Essen,Duisburg,Berliner Platz 6-8,45127,710,240,NaN,0.741,0.653,7.004285,51.462607,NaN,NaN,NaN,2.4,2.7,2.9,2.6,2.4,2.4,3.2,2.2,2.4,2.1,2.4,2.6,NaN,470,0,0,0,0,0,1
1241,176,604222,Fachbereich Bildungswissenschaften an der Uni Duisburg-Essen/Essen,Duisburg,Universitätsstraße 12,45141,110,<NA>,0.500000,NaN,NaN,7.004285,51.462607,NaN,NaN,0.00,NaN,2.0,2.9,1.5,2.0,NaN,2.8,NaN,1.4,1.7,1.9,2.0,NaN,<NA>,0,0,0,0,0,1
1325,272,604374,Fachbereich Bildungswissenschaft an der Alanus HS/Alfter (priv.),Alfter,Villestraße 3,53347,490,170,NaN,0.875,0.610,7.028870,50.745580,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,320,0,0,0,0,0,1
1671,440,100232,Fachbereich 2 an der HS Bremerhaven,Bremerhaven,An der Karlstadt 8,27568,520,<NA>,0.785714,0.784,0.571,8.583100,53.539938,0.500000,NaN,NaN,2.0,1.9,2.1,1.6,1.9,NaN,2.1,2.1,2.0,1.9,2.5,2.0,NaN,<NA>,0,0,0,0,0,1
1673,440,400401,Fachbereich 2 an der HS Bremerhaven,Bremerhaven,An der Karlstadt 8,27568,220,<NA>,0.785714,NaN,NaN,8.583100,53.539938,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,0,0,0,0,0,1
1677,440,100322,Fachbereich 2 an der HS Bremerhaven,Bremerhaven,An der Karlstadt 8,27568,190,30,0.666667,1.000,NaN,8.583100,53.539938,0.153846,0.076923,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,160,0,0,0,0,0,1
1678,440,11060,Fachbereich 2 an der HS Bremerhaven,Bremerhaven,An der Karlstadt 8,27568,300,40,0.666667,0.340,0.955,8.583100,53.539938,0.384615,0.538462,NaN,2.1,2.4,2.3,NaN,3.0,NaN,NaN,NaN,2.3,2.1,2.2,2.4,NaN,260,0,0,0,0,0,1
1750,454,100025,Wiesbaden Business School an der HS RheinMain/Wiesbaden,Wiesbaden,Bleichstraße 44,65183,2630,300,NaN,NaN,NaN,8.218647,50.080541,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2330,0,0,0,0,0,1
1755,454,410534,Wiesbaden Business School an der HS RheinMain/Wiesbaden,Wiesbaden,Bleichstraße 44,65183,550,<NA>,NaN,NaN,NaN,8.218647,50.080541,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,0,0,0,0,0,1
1890,500,7017,Peter Behrens School of Arts an der HS Düsseldorf,Düsseldorf,Münsterstraße 156,40476,850,160,NaN,0.769,0.814,6.790647,51.246149,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,690,0,0,0,0,0,1
1965,522,420167,Fachbereich II: Heilpädagogik und Pflege an der EvHS Rheinland/Bochum,Bochum,Immanuel-Kant-Straße 18-20,44803,230,<NA>,0.666667,0.900,NaN,7.252477,51.473470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,0,0,0,0,0,1
2109,576,604416,Fachbereich SciTec an der EAH Jena,Jena,Carl-Zeiss-Promenade 2,7745,150,90,0.500000,0.760,0.368,11.569632,50.919207,0.111111,0.000000,0.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60,0,0,0,0,0,1
2110,576,500468,Fachbereich SciTec an der EAH Jena,Jena,Carl-Zeiss-Promenade 2,7745,<NA>,<NA>,0.500000,NaN,NaN,11.569632,50.919207,NaN,NaN,0.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,0,0,0,0,0,1
2115,576,500468,Fachbereich SciTec an der EAH Jena,Jena,Carl-Zeiss-Promenade 2,7745,<NA>,<NA>,0.500000,NaN,NaN,11.569632,50.919207,NaN,NaN,0.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,0,0,0,0,0,1
2118,576,604415,Fachbereich SciTec an der EAH Jena,Jena,Carl-Zeiss-Promenade 2,7745,<NA>,<NA>,0.571429,NaN,NaN,11.569632,50.919207,NaN,NaN,0.07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,0,0,0,0,0,1
2146,628,410248,"Fachbereich Handels- und Logistikmanagement an der EuFH Rhein/Erft, Brühl (priv.)",Brühl,Kaiserstraße 6,50321,<NA>,<NA>,NaN,NaN,NaN,6.905549,50.833814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,0,0,0,0,0,1
2147,628,440194,"Fachbereich General Management an der EuFH Rhein/Erft, Brühl (priv.)",Brühl,Kaiserstraße 11,50321,<NA>,<NA>,NaN,NaN,NaN,6.905549,50.833814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,0,0,0,0,0,1
2148,628,603107,"Business School an der EuFH Rhein/Erft, Brühl (priv.)",Brühl,Kaiserstraße 6,50321,870,150,NaN,NaN,NaN,6.905549,50.833814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,720,0,0,0,0,0,1
2165,664,500563,Fachbereich 3 an der HS Ruhr West/Mülheim,Mülheim an der Ruhr,Duisburger Str. 100,45479,<NA>,<NA>,0.571429,NaN,NaN,6.823317,51.477405,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,0,0,0,0,0,1
2166,664,600664,Fachbereich 2 an der HS Ruhr West/Mülheim,Mülheim an der Ruhr,Mellinghofer Straße 55; Gebäude 27a,45473,1910,350,NaN,NaN,NaN,6.823317,51.477405,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1560,0,0,0,0,0,1
2167,664,500565,Fachbereich 4 an der HS Ruhr West/Mülheim,Mülheim an der Ruhr,Duisburger Str. 100,45479,360,130,0.571429,0.857,0.346,6.823317,51.477405,0.111111,0.222222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,230,0,0,0,0,0,1
2168,664,500564,Fachbereich 3 an der HS Ruhr West/Mülheim,Mülheim an der Ruhr,Duisburger Str. 100,45479,<NA>,<NA>,0.571429,NaN,NaN,6.823317,51.477405,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,0,0,0,0,0,1
2169,664,500638,Fachbereich 4 an der HS Ruhr West/Mülheim,Mülheim an der Ruhr,Duisburger Str. 100,45479,160,<NA>,NaN,NaN,NaN,6.823317,51.477405,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,0,0,0,0,0,1
2170,664,602106,Fachbereich 3 an der HS Ruhr West/Mülheim,Mülheim an der Ruhr,Wiesenstraße 36,45473,550,<NA>,NaN,0.432,NaN,6.823317,51.477405,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,0,0,0,0,0,1
2202,754,600751,Fachbereich Pflege an der Akkon HS/Berlin (priv.),Berlin,Colditzstraße 34-36,12099,110,<NA>,NaN,NaN,NaN,13.395163,52.454534,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,0,0,0,0,0,1
2206,762,602157,Fachbereich Logistik an der SRH HS NRW (priv.),Hamm,Platz der Deutschen Einheit 1,59065,320,220,0.583333,0.625,NaN,7.810879,51.679201,0.461538,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100,0,0,0,0,0,1
2224,778,604183,Studienrichtung Pflege an der BA GS Saarland (priv.),Saarbrücken,Konrad-Zuse-Straße 31a,66115,<NA>,<NA>,NaN,NaN,NaN,6.955135,49.339239,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,0,0,0,0,0,1

In [80]:
fbs.drop('sum', axis = 1, inplace = True)