In [64]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', -1)

/var/folders/1y/xsmfy4rd3_qcqffqthwtp0th0000gn/T/ipykernel_25885/1185836227.py:8: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  pd.set_option('display.max_colwidth', -1)

In [ ]:
unis = pd.read_csv('./data/unis_cleaned.csv')
studis = pd.read_csv('./data/studis_cleaned.csv')
fbs = pd.read_csv('./data/fbs_cleaned.csv')

In [ ]:
unis.drop('Unnamed: 0', axis = 1, inplace = True)

In [ ]:
studis.drop('Unnamed: 0', axis = 1, inplace = True)

In [ ]:
fbs.drop('Unnamed: 0', axis = 1, inplace = True)

In [ ]:
unis['total_students'] = unis['total_students'].convert_dtypes(int)
unis['total_students_loc'] = unis['total_students_loc'].convert_dtypes(int)

In [ ]:
studis['semester'] = studis['semester'].convert_dtypes(int)

In [ ]:
fbs.head()
col_names = ['total_stud', 'total_stud_ma', 'total_students_la', 'total_students_ma_appr']

In [ ]:
for element in col_names:
    fbs[element] = fbs[element].convert_dtypes(int)

In [48]:
def definer_mg(x):
    x = x.lower() 
    if  x.find('medi') > -1 or x.find('medi') > -1 or x.find('gesund') > -1 or x.find('pharma') > -1 or x.find('spo') > -1 or x.find('psy') > -1  or x.find('lebe') > -1 or x.find('human') > -1 or x.find('leben') > -1:
        return 1
    else:
        return 0
def definer_mn(x):
    x = x.lower() 
    if x.find('math') > -1 or x.find('phy') > -1 or x.find('tech') > -1 or x.find('chem') > -1 or x.find('bio') > -1 or x.find('mint') > -1 or x.find('nat') > -1 or x.find('geo') > -1:
        return 1
    else:
        return 0
def definer_rws(x): 
    x = x.lower() 
    if x.find('wirt') > -1 or x.find('sozial') > -1 or x.find('recht') > -1  or x.find('jur') > -1  or x.find('betr') > -1 or x.find('gese') > -1 or x.find('pol') > -1  or x.find('ver') > -1 or x.find('geist') > -1 or x.find('volksw') > -1 or x.find('bwl') > -1:
        return 1
    else:
        return 0
def definer_sk(x):
    x = x.lower()  
    if x.find('engl') > -1 or x.find('eng.') > -1 or x.find('eng-') > -1 or x.find('phil') > -1 or x.find('phil') > -1 or x.find('franz') > -1 or x.find('amer') > -1 or x.find('angl') > -1  or x.find('jap') > -1 or x.find('asia') > -1 or x.find('lingu') > -1 or x.find('kultur') > -1 or x.find('literat') > -1:
        return 1
    else:
        return 0
def definer_ii(x):
    x = x.lower() 
    if x.find('ingenieur') > -1 or x.find('info') > -1 or x.find('tech') > -1 or x.find('masch') > -1 or x.find('elektro') > -1 or x.find('archit') > -1 or x.find('bau') > -1 or x.find('luft') > -1 or x.find('raum') > -1 :
        return 1
    else:
        return 0

In [ ]:
fbs.rename(columns = {  'name_fb' : 'name',}, inplace = True)
rn_cols = fbs.columns.to_list()
rn_cols.remove('id_uni')
rn_cols.remove('id_fak')
for element in rn_cols:
    fbs.rename(columns = {f'{element}' : f'fbs_{element}'}, inplace = True)

In [ ]:
fbs['fbs_med_d'] = fbs['fbs_name'].apply(lambda x: definer_mg(x))
fbs['fbs_nat_d'] = fbs['fbs_name'].apply(lambda x: definer_mn(x))
fbs['fbs_rws_d'] = fbs['fbs_name'].apply(lambda x: definer_rws(x))
fbs['fbs_spr_d'] = fbs['fbs_name'].apply(lambda x: definer_sk(x))
fbs['fbs_ing_d'] = fbs['fbs_name'].apply(lambda x: definer_ii(x))

In [ ]:
unis.rename(columns = { 'name_uni' : 'name',
                        'type_uni' : 'type'}, inplace = True)
rn_cols2 = unis.columns.to_list()
rn_cols2.remove('id_uni')
for element in rn_cols2:
   unis.rename(columns = {f'{element}' : f'uni_{element}'}, inplace = True)
unis = unis.drop_duplicates('id_uni')
unis.head()

In [ ]:
unis.head()

In [ ]:
unis.shape

In [ ]:
fbs.shape

In [ ]:
uni_fbs = pd.merge(fbs, unis, how = 'left', on = 'id_uni')

In [ ]:
uni_fbs.head()

In [ ]:
uni_fbs.shape

In [ ]:
stud_cols = studis.columns.to_list()
stud_cols.remove('id_uni')
stud_cols.remove('id_fak')
stud_cols.remove('id_stud')
for element in stud_cols:
   studis.rename(columns = {f'{element}' : f'std_{element}'}, inplace = True)
studis.head()

In [ ]:
studis.shape

In [ ]:
studis = studis.drop_duplicates('id_stud')
studis.shape

In [ ]:
def clean(x):
    try:
        return int(x)
    except:
        return np.nan

In [ ]:
studis['std_total_grads_year'] = studis['std_total_grads_year'].apply(lambda x: clean(str(x).replace('<', '').replace(' *', '')))

In [ ]:
studis['std_total_grads_year'] = studis['std_total_grads_year'].convert_dtypes(int)

In [ ]:
studis['std_total_starter_year'] = studis['std_total_starter_year'].apply(lambda x: clean(str(x).replace('<', '').replace(' *', '')))
studis['std_total_starter_year'] = studis['std_total_starter_year'].convert_dtypes(int)

In [ ]:
studis['std_total_starter_year'].unique()

In [ ]:
studis['std_total_stds'] = studis['std_total_stds'].apply(lambda x: clean(str(x).replace('<', '').replace(' *','')))
studis['std_total_stds'] = studis['std_total_stds'].convert_dtypes(int)

In [ ]:
# studis[studis['total_stds'] == 'im Aufbau']
studis['std_total_stds'].value_counts()

In [ ]:
import psycopg2
from sql import host, port, database, user, password, engine
#Specify which table within your database you want to push your data to. Give your table an unambiguous name.
table_name = 'uni_fbs'
# If the specified table doesn't exist yet, it will be created
# With 'replace', your data will be replaced if the table already exists.
# This will take a minute or two...
# Write records stored in a dataframe to SQL database
if engine!=None:
    try:
        #df_selected_airports
        uni_fbs.to_sql(name=table_name, # Name of SQL table
                        con=engine, # Engine or connection
                        if_exists='replace', # Drop the table before inserting new values 
                        schema='tomorrows_talents', # Use schmea that was defined earlier
                        index=False, # Write DataFrame index as a column
                        chunksize=5000, # Specify the number of rows in each batch to be written at a time
                        method='multi') # Pass multiple values in a single INSERT clause
        print(f"The {table_name} table was imported successfully.")
    # Error handling
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
        engine = None

In [1]:
import psycopg2
from sql import host, port, database, user, password, engine
#Specify which table within your database you want to push your data to. Give your table an unambiguous name.
table_name = 'studis'
# If the specified table doesn't exist yet, it will be created
# With 'replace', your data will be replaced if the table already exists.
# This will take a minute or two...
# Write records stored in a dataframe to SQL database
if engine!=None:
    try:
        #df_selected_airports
        studis.to_sql(name=table_name, # Name of SQL table
                        con=engine, # Engine or connection
                        if_exists='replace', # Drop the table before inserting new values 
                        schema='tomorrows_talents', # Use schmea that was defined earlier
                        index=False, # Write DataFrame index as a column
                        chunksize=5000, # Specify the number of rows in each batch to be written at a time
                        method='multi') # Pass multiple values in a single INSERT clause
        print(f"The {table_name} table was imported successfully.")
    # Error handling
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
        engine = None

name 'studis' is not defined

In [65]:
from sql import get_data

In [52]:
uni_fbs2 = get_data('SELECT * FROM tomorrows_talents.uni_fbs')

In [4]:
sum_uni_fbs = uni_fbs2.groupby('fbs_name').sum()

In [5]:
sum_uni_fbs.head()

,id_uni,id_fak,fbs_plz,fbs_total_stud,fbs_total_stud_ma,fbs_support_start,fbs_tframe_grad_ba,fbs_tframe_grad_ma,fbs_lon,fbs_lat,...,uni_total_nat_math,uni_total_law_econ_social,uni_total_lang_cult,uni_total_engineer_info,uni_total_other,uni_total_bachelor,uni_total_master,uni_total_lehramt,uni_total_dipl_magis_staatsex,uni_total_other_grad
fbs_name,,,,,,,,,,,,,,,,,,,,,
Agrar- und Umweltwissenschaftliche Fakultät an der Uni Rostock,82,1600816,18059,0.0,0.0,0.428571,0.000,0.000,12.133682,54.087937,...,2015,3381,2119,2704,598,4824,2197,3472,2392,104
BWL-Studiengänge (Dortmund) an der ISM/Dortmund (priv.),518,101143,44227,740.0,250.0,0.785714,0.626,1.000,7.408038,51.489733,...,0,2589,0,0,0,2014,574,0,0,0
Betriebswirtschaftliche Studiengänge (duale Stg.) an der HSBA Hamburg (priv.),654,430632,20459,0.0,210.0,0.571429,0.000,0.000,9.984816,53.547423,...,0,1000,0,67,0,746,321,0,0,0
Betriebswirtschaftliche und Management Studiengänge an der Steinbeis HS Berlin (priv.),604,1600769,10247,6390.0,2030.0,0.000000,0.810,0.749,13.473269,52.509301,...,0,7312,0,338,0,5896,3010,0,0,0
Biologische Fakultät an der Uni Göttingen,88,30130,37073,640.0,200.0,0.428571,0.915,0.667,9.938132,51.533743,...,6002,9682,5368,1206,4192,15352,6786,1477,6092,422

In [6]:
sum_uni_fbs.reset_index(inplace=True)

In [7]:
sum_uni_fbs.shape

(1143, 61)

In [8]:
avg_uni_fbs = uni_fbs2.groupby('fbs_name').mean()

In [9]:
avg_uni_fbs.head()

,id_uni,id_fak,fbs_plz,fbs_total_stud,fbs_total_stud_ma,fbs_support_start,fbs_tframe_grad_ba,fbs_tframe_grad_ma,fbs_lon,fbs_lat,...,uni_total_nat_math,uni_total_law_econ_social,uni_total_lang_cult,uni_total_engineer_info,uni_total_other,uni_total_bachelor,uni_total_master,uni_total_lehramt,uni_total_dipl_magis_staatsex,uni_total_other_grad
fbs_name,,,,,,,,,,,,,,,,,,,,,
Agrar- und Umweltwissenschaftliche Fakultät an der Uni Rostock,82.0,1600816.0,18059.0,NaN,NaN,0.428571,NaN,NaN,12.133682,54.087937,...,2015.0,3381.0,2119.0,2704.0,598.0,4824.0,2197.0,3472.0,2392.0,104.0
BWL-Studiengänge (Dortmund) an der ISM/Dortmund (priv.),518.0,101143.0,44227.0,740.0,250.0,0.785714,0.626,1.000,7.408038,51.489733,...,0.0,2589.0,0.0,0.0,0.0,2014.0,574.0,0.0,0.0,0.0
Betriebswirtschaftliche Studiengänge (duale Stg.) an der HSBA Hamburg (priv.),654.0,430632.0,20459.0,NaN,210.0,0.571429,NaN,NaN,9.984816,53.547423,...,0.0,1000.0,0.0,67.0,0.0,746.0,321.0,0.0,0.0,0.0
Betriebswirtschaftliche und Management Studiengänge an der Steinbeis HS Berlin (priv.),604.0,1600769.0,10247.0,6390.0,2030.0,NaN,0.810,0.749,13.473269,52.509301,...,0.0,7312.0,0.0,338.0,0.0,5896.0,3010.0,0.0,0.0,0.0
Biologische Fakultät an der Uni Göttingen,88.0,30130.0,37073.0,640.0,200.0,0.428571,0.915,0.667,9.938132,51.533743,...,6002.0,9682.0,5368.0,1206.0,4192.0,15352.0,6786.0,1477.0,6092.0,422.0

In [10]:
avg_uni_fbs.reset_index(inplace= True)

In [11]:
avg_uni_fbs.shape

(1143, 61)

In [12]:
uni_fbs2.shape

(2251, 69)

In [13]:
drop_uni_fbs = uni_fbs2.drop_duplicates('fbs_name').copy()

In [14]:
drop_uni_fbs.shape

(1143, 69)

In [15]:
drop_uni_fbs.sort_values('fbs_name', ascending = True, inplace = True)

In [16]:
drop_uni_fbs.head()

,id_uni,id_fak,fbs_name,fbs_city,fbs_street_nr,fbs_plz,fbs_total_stud,fbs_total_stud_ma,fbs_support_start,fbs_tframe_grad_ba,...,uni_total_nat_math,uni_total_law_econ_social,uni_total_lang_cult,uni_total_engineer_info,uni_total_other,uni_total_bachelor,uni_total_master,uni_total_lehramt,uni_total_dipl_magis_staatsex,uni_total_other_grad
636,82,1600816,Agrar- und Umweltwissenschaftliche Fakultät an...,Rostock,Justus-von-Liebig-Weg 6,18059,NaN,NaN,0.428571,NaN,...,2015,3381,2119,2704,598,4824,2197,3472,2392,104
1960,518,101143,BWL-Studiengänge (Dortmund) an der ISM/Dortmun...,Dortmund,Otto-Hahn-Straße 19,44227,740.0,250.0,0.785714,0.626,...,0,2589,0,0,0,2014,574,0,0,0
2166,654,430632,Betriebswirtschaftliche Studiengänge (duale St...,Hamburg,Willy-Brandt-Straße 75,20459,NaN,210.0,0.571429,NaN,...,0,1000,0,67,0,746,321,0,0,0
2136,604,1600769,Betriebswirtschaftliche und Management Studien...,Berlin,Gürtelstraße 29A/30,10247,6390.0,2030.0,NaN,0.810,...,0,7312,0,338,0,5896,3010,0,0,0
692,88,30130,Biologische Fakultät an der Uni Göttingen,Göttingen,Goßlerstraße 14,37073,640.0,200.0,0.428571,0.915,...,6002,9682,5368,1206,4192,15352,6786,1477,6092,422

In [17]:
drop_uni_fbs.reset_index(inplace=True)

In [18]:
drop_uni_fbs['fbs_total_stud'] = sum_uni_fbs['fbs_total_stud']
drop_uni_fbs['fbs_total_stud_ma'] = sum_uni_fbs['fbs_total_stud_ma']

In [19]:
avg_cols = ['fbs_support_start', 'fbs_tframe_grad_ba', 'fbs_tframe_grad_ba', 'fbs_tframe_grad_ma','fbs_int_ba', 'fbs_int_ma', 'fbs_foreign_spot', 'fbs_sup_doz',
              'fbs_sup_in_studies', 'fbs_curriculum', 'fbs_students_orga',
              'fbs_exams', 'fbs_research_conn', 'fbs_offer_joborientation',
              'fbs_supp_exchange', 'fbs_faculties', 'fbs_bib',
              'fbs_it_infrastructure', 'fbs_grade_overall']

In [20]:
for element in avg_cols:
    drop_uni_fbs[element] = avg_uni_fbs[element]

In [21]:
drop_uni_fbs.head()

,index,id_uni,id_fak,fbs_name,fbs_city,fbs_street_nr,fbs_plz,fbs_total_stud,fbs_total_stud_ma,fbs_support_start,...,uni_total_nat_math,uni_total_law_econ_social,uni_total_lang_cult,uni_total_engineer_info,uni_total_other,uni_total_bachelor,uni_total_master,uni_total_lehramt,uni_total_dipl_magis_staatsex,uni_total_other_grad
0,636,82,1600816,Agrar- und Umweltwissenschaftliche Fakultät an...,Rostock,Justus-von-Liebig-Weg 6,18059,0.0,0.0,0.428571,...,2015,3381,2119,2704,598,4824,2197,3472,2392,104
1,1960,518,101143,BWL-Studiengänge (Dortmund) an der ISM/Dortmun...,Dortmund,Otto-Hahn-Straße 19,44227,740.0,250.0,0.785714,...,0,2589,0,0,0,2014,574,0,0,0
2,2166,654,430632,Betriebswirtschaftliche Studiengänge (duale St...,Hamburg,Willy-Brandt-Straße 75,20459,0.0,210.0,0.571429,...,0,1000,0,67,0,746,321,0,0,0
3,2136,604,1600769,Betriebswirtschaftliche und Management Studien...,Berlin,Gürtelstraße 29A/30,10247,6390.0,2030.0,NaN,...,0,7312,0,338,0,5896,3010,0,0,0
4,692,88,30130,Biologische Fakultät an der Uni Göttingen,Göttingen,Goßlerstraße 14,37073,640.0,200.0,0.428571,...,6002,9682,5368,1206,4192,15352,6786,1477,6092,422

In [39]:
drop_uni_fbs['fbs_spr_d'] = drop_uni_fbs['fbs_name'].apply(lambda x: definer_sk(x))

In [49]:
drop_uni_fbs['fbs_ing_d'] = drop_uni_fbs['fbs_name'].apply(lambda x: definer_ii(x))

In [50]:
import psycopg2
from sql import host, port, database, user, password, engine
#Specify which table within your database you want to push your data to. Give your table an unambiguous name.
table_name = 'uni_fbs2'
# If the specified table doesn't exist yet, it will be created
# With 'replace', your data will be replaced if the table already exists.
# This will take a minute or two...
# Write records stored in a dataframe to SQL database
if engine!=None:
    try:
        #df_selected_airports
        drop_uni_fbs.to_sql(name=table_name, # Name of SQL table
                        con=engine, # Engine or connection
                        if_exists='replace', # Drop the table before inserting new values 
                        schema='tomorrows_talents', # Use schmea that was defined earlier
                        index=False, # Write DataFrame index as a column
                        chunksize=5000, # Specify the number of rows in each batch to be written at a time
                        method='multi') # Pass multiple values in a single INSERT clause
        print(f"The {table_name} table was imported successfully.")
    # Error handling
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
        engine = None

The uni_fbs2 table was imported successfully.

In [27]:
drop_uni_fbs.groupby(['id_uni','fbs_city', 'fbs_name'], axis = 0).sum()

                                                                       index  \
id_uni fbs_city    fbs_name
2      Freiburg    Fakultät für Biologie an der Uni Freiburg               2
                   Fakultät für Chemie und Pharmazie an der Uni Fr...      1
                   Fakultät für Mathematik und Physik an der Uni F...     12
                   Fakultät für Umwelt und Natürliche Ressourcen a...      6
                   Medizinische Fakultät an der Uni Freiburg              13
...                                                                      ...
834    Garching    Fakultät für Mathematik an der TU München/Garching   2245
                   Fakultät für Physik an der TU München/Garching       2247
                   Munich School of Engineering an der TU München/...   2239
854    Senftenberg Fakultät 2: Umwelt und Naturwissenschaften an d...   2236
878    Wiesbaden   EBS Law School an der EBS Universität/Wiesbaden...   2250

                                                                        id_fak  \
id_uni fbs_city    fbs_name
2      Freiburg    Fakultät für Biologie an der Uni Freiburg            420102
                   Fakultät für Chemie und Pharmazie an der Uni Fr...  1200001
                   Fakultät für Mathematik und Physik an der Uni F...   400002
                   Fakultät für Umwelt und Natürliche Ressourcen a...   430062
                   Medizinische Fakultät an der Uni Freiburg            420021
...                                                                        ...
834    Garching    Fakultät für Mathematik an der TU München/Garching   400047
                   Fakultät für Physik an der TU München/Garching       400048
                   Munich School of Engineering an der TU München/...   500503
854    Senftenberg Fakultät 2: Umwelt und Naturwissenschaften an d...   606271
878    Wiesbaden   EBS Law School an der EBS Universität/Wiesbaden...   600670

                                                                       fbs_plz  \
id_uni fbs_city    fbs_name
2      Freiburg    Fakultät für Biologie an der Uni Freiburg             79104
                   Fakultät für Chemie und Pharmazie an der Uni Fr...    79104
                   Fakultät für Mathematik und Physik an der Uni F...    79104
                   Fakultät für Umwelt und Natürliche Ressourcen a...    79085
                   Medizinische Fakultät an der Uni Freiburg             79110
...                                                                        ...
834    Garching    Fakultät für Mathematik an der TU München/Garching    85748
                   Fakultät für Physik an der TU München/Garching        85747
                   Munich School of Engineering an der TU München/...    85748
854    Senftenberg Fakultät 2: Umwelt und Naturwissenschaften an d...     1968
878    Wiesbaden   EBS Law School an der EBS Universität/Wiesbaden...    65189

                                                                       fbs_total_stud  \
id_uni fbs_city    fbs_name
2      Freiburg    Fakultät für Biologie an der Uni Freiburg                   1260.0
                   Fakultät für Chemie und Pharmazie an der Uni Fr...          1750.0
                   Fakultät für Mathematik und Physik an der Uni F...          1030.0
                   Fakultät für Umwelt und Natürliche Ressourcen a...           560.0
                   Medizinische Fakultät an der Uni Freiburg                   3840.0
...                                                                               ...
834    Garching    Fakultät für Mathematik an der TU München/Garching          1360.0
                   Fakultät für Physik an der TU München/Garching              1990.0
                   Munich School of Engineering an der TU München/...             0.0
854    Senftenberg Fakultät 2: Umwelt und Naturwissenschaften an d...            30.0
878    Wiesbaden   EBS Law School an der EBS Universität/Wiesbaden...           440.0

                                                                       fbs_total_stud_ma  \
id_uni fbs_city    fbs_name
2      Freiburg    Fakultät für Biologie an der Uni Freiburg                       233.0
                   Fakultät für Chemie und Pharmazie an der Uni Fr...              324.0
                   Fakultät für Mathematik und Physik an der Uni F...              250.0
                   Fakultät für Umwelt und Natürliche Ressourcen a...              104.0
                   Medizinische Fakultät an der Uni Freiburg                       709.0
...                                                                                  ...
834    Garching    Fakultät für Mathematik an der TU München/Garching              710.0
                   Fakultät für Physik an der TU München/Garching                  560.0
                   Munich School of Engineering an der TU München/...                0.0
854    Senftenberg Fakultät 2: Umwelt und Naturwissenschaften an d...                6.0
878    Wiesbaden   EBS Law School an der EBS Universität/Wiesbaden...               81.0

                                                                       fbs_support_start  \
id_uni fbs_city    fbs_name
2      Freiburg    Fakultät für Biologie an der Uni Freiburg                    0.785714
                   Fakultät für Chemie und Pharmazie an der Uni Fr...           0.673077
                   Fakultät für Mathematik und Physik an der Uni F...           0.785714
                   Fakultät für Umwelt und Natürliche Ressourcen a...           0.607143
                   Medizinische Fakultät an der Uni Freiburg                    0.000000
...                                                                                  ...
834    Garching    Fakultät für Mathematik an der TU München/Garching           0.785714
                   Fakultät für Physik an der TU München/Garching               0.714286
                   Munich School of Engineering an der TU München/...           0.642857
854    Senftenberg Fakultät 2: Umwelt und Naturwissenschaften an d...           0.571429
878    Wiesbaden   EBS Law School an der EBS Universität/Wiesbaden...           1.000000

                                                                       fbs_tframe_grad_ba  \
id_uni fbs_city    fbs_name
2      Freiburg    Fakultät für Biologie an der Uni Freiburg                     0.882000
                   Fakultät für Chemie und Pharmazie an der Uni Fr...            0.679000
                   Fakultät für Mathematik und Physik an der Uni F...            0.909000
                   Fakultät für Umwelt und Natürliche Ressourcen a...            0.846000
                   Medizinische Fakultät an der Uni Freiburg                     0.926333
...                                                                                   ...
834    Garching    Fakultät für Mathematik an der TU München/Garching            0.806000
                   Fakultät für Physik an der TU München/Garching                0.880000
                   Munich School of Engineering an der TU München/...            0.000000
854    Senftenberg Fakultät 2: Umwelt und Naturwissenschaften an d...            0.000000
878    Wiesbaden   EBS Law School an der EBS Universität/Wiesbaden...            0.000000

                                                                       fbs_tframe_grad_ma  \
id_uni fbs_city    fbs_name
2      Freiburg    Fakultät für Biologie an der Uni Freiburg                        0.549
                   Fakultät für Chemie und Pharmazie an der Uni Fr...               0.537
                   Fakultät für Mathematik und Physik an der Uni F...               0.254
                   Fakultät für Umwelt und Natürliche Ressourcen a...               0.109
                   Medizinische Fakultät an der Uni Freiburg                        0.000
...                                                                                   ...
834    Garching    Fakultät für Mathematik an der TU München/Garching               0.385
                   Fakultät für Physik an der TU München/Garching                   0.575
                   Munich School of Engineering an der TU München/...               0.000
854    Senftenberg Fakultät 2: Umwelt und Naturwissenschaften an d...               0.000
878    Wiesbaden   EBS Law School an der EBS Universität/Wiesbaden...               0.000

                                                                         fbs_lon  \
id_uni fbs_city    fbs_name
2      Freiburg    Fakultät für Biologie an der Uni Freiburg            7.847936
                   Fakultät für Chemie und Pharmazie an der Uni Fr...   7.847936
                   Fakultät für Mathematik und Physik an der Uni F...   7.847936
                   Fakultät für Umwelt und Natürliche Ressourcen a...   7.847936
                   Medizinische Fakultät an der Uni Freiburg            7.847936
...                                                                          ...
834    Garching    Fakultät für Mathematik an der TU München/Garching  11.671707
                   Fakultät für Physik an der TU München/Garching      11.671707
                   Munich School of Engineering an der TU München/...  11.671707
854    Senftenberg Fakultät 2: Umwelt und Naturwissenschaften an d...  13.986841
878    Wiesbaden   EBS Law School an der EBS Universität/Wiesbaden...   8.247985

                                                                         fbs_lat  \
id_uni fbs_city    fbs_name
2      Freiburg    Fakultät für Biologie an der Uni Freiburg           47.998253
                   Fakultät für Chemie und Pharmazie an der Uni Fr...  47.998253
                   Fakultät für Mathematik und Physik an der Uni F...  47.998253
                   Fakultät für Umwelt und Natürliche Ressourcen a...  47.998253
                   Medizinische Fakultät an der Uni Freiburg           47.998253
...                                                                          ...
834    Garching    Fakultät für Mathematik an der TU München/Garching  48.265888
                   Fakultät für Physik an der TU München/Garching      48.265888
                   Munich School of Engineering an der TU München/...  48.265888
854    Senftenberg Fakultät 2: Umwelt und Naturwissenschaften an d...  51.520840
878    Wiesbaden   EBS Law School an der EBS Universität/Wiesbaden...  50.071232

                                                                       ...  \
id_uni fbs_city    fbs_name                                            ...
2      Freiburg    Fakultät für Biologie an der Uni Freiburg           ...
                   Fakultät für Chemie und Pharmazie an der Uni Fr...  ...
                   Fakultät für Mathematik und Physik an der Uni F...  ...
                   Fakultät für Umwelt und Natürliche Ressourcen a...  ...
                   Medizinische Fakultät an der Uni Freiburg           ...
...                                                                    ...
834    Garching    Fakultät für Mathematik an der TU München/Garching  ...
                   Fakultät für Physik an der TU München/Garching      ...
                   Munich School of Engineering an der TU München/...  ...
854    Senftenberg Fakultät 2: Umwelt und Naturwissenschaften an d...  ...
878    Wiesbaden   EBS Law School an der EBS Universität/Wiesbaden...  ...

                                                                       uni_total_nat_math  \
id_uni fbs_city    fbs_name
2      Freiburg    Fakultät für Biologie an der Uni Freiburg                         4445
                   Fakultät für Chemie und Pharmazie an der Uni Fr...                4445
                   Fakultät für Mathematik und Physik an der Uni F...                4445
                   Fakultät für Umwelt und Natürliche Ressourcen a...                4445
                   Medizinische Fakultät an der Uni Freiburg                         4445
...                                                                                   ...
834    Garching    Fakultät für Mathematik an der TU München/Garching               12196
                   Fakultät für Physik an der TU München/Garching                   12196
                   Munich School of Engineering an der TU München/...               12196
854    Senftenberg Fakultät 2: Umwelt und Naturwissenschaften an d...                1508
878    Wiesbaden   EBS Law School an der EBS Universität/Wiesbaden...                   0

                                                                       uni_total_law_econ_social  \
id_uni fbs_city    fbs_name
2      Freiburg    Fakultät für Biologie an der Uni Freiburg                                6151
                   Fakultät für Chemie und Pharmazie an der Uni Fr...                       6151
                   Fakultät für Mathematik und Physik an der Uni F...                       6151
                   Fakultät für Umwelt und Natürliche Ressourcen a...                       6151
                   Medizinische Fakultät an der Uni Freiburg                                6151
...                                                                                          ...
834    Garching    Fakultät für Mathematik an der TU München/Garching                          0
                   Fakultät für Physik an der TU München/Garching                              0
                   Munich School of Engineering an der TU München/...                          0
854    Senftenberg Fakultät 2: Umwelt und Naturwissenschaften an d...                        435
878    Wiesbaden   EBS Law School an der EBS Universität/Wiesbaden...                       1828

                                                                       uni_total_lang_cult  \
id_uni fbs_city    fbs_name
2      Freiburg    Fakultät für Biologie an der Uni Freiburg                          5093
                   Fakultät für Chemie und Pharmazie an der Uni Fr...                 5093
                   Fakultät für Mathematik und Physik an der Uni F...                 5093
                   Fakultät für Umwelt und Natürliche Ressourcen a...                 5093
                   Medizinische Fakultät an der Uni Freiburg                          5093
...                                                                                    ...
834    Garching    Fakultät für Mathematik an der TU München/Garching                    0
                   Fakultät für Physik an der TU München/Garching                        0
                   Munich School of Engineering an der TU München/...                    0
854    Senftenberg Fakultät 2: Umwelt und Naturwissenschaften an d...                    0
878    Wiesbaden   EBS Law School an der EBS Universität/Wiesbaden...                    0

                                                                       uni_total_engineer_info  \
id_uni fbs_city    fbs_name
2      Freiburg    Fakultät für Biologie an der Uni Freiburg                              2210
                   Fakultät für Chemie und Pharmazie an der Uni Fr...                     2210
                   Fakultät für Mathematik und Physik an der Uni F...                     2210
                   Fakultät für Umwelt und Natürliche Ressourcen a...                     2210
                   Medizinische Fakultät an der Uni Freiburg                              2210
...                                                                                        ...
834    Garching    Fakultät für Mathematik an der TU München/Garching                    29571
                   Fakultät für Physik an der TU München/Garching                        29571
                   Munich School of Engineering an der TU München/...                    29571
854    Senftenberg Fakultät 2: Umwelt und Naturwissenschaften an d...                     2670
878    Wiesbaden   EBS Law School an der EBS Universität/Wiesbaden...                        0

                                                                       uni_total_other  \
id_uni fbs_city    fbs_name
2      Freiburg    Fakultät für Biologie an der Uni Freiburg                      2306
                   Fakultät für Chemie und Pharmazie an der Uni Fr...             2306
                   Fakultät für Mathematik und Physik an der Uni F...             2306
                   Fakultät für Umwelt und Natürliche Ressourcen a...             2306
                   Medizinische Fakultät an der Uni Freiburg                      2306
...                                                                                ...
834    Garching    Fakultät für Mathematik an der TU München/Garching                0
                   Fakultät für Physik an der TU München/Garching                    0
                   Munich School of Engineering an der TU München/...                0
854    Senftenberg Fakultät 2: Umwelt und Naturwissenschaften an d...                0
878    Wiesbaden   EBS Law School an der EBS Universität/Wiesbaden...                0

                                                                       uni_total_bachelor  \
id_uni fbs_city    fbs_name
2      Freiburg    Fakultät für Biologie an der Uni Freiburg                        10380
                   Fakultät für Chemie und Pharmazie an der Uni Fr...               10380
                   Fakultät für Mathematik und Physik an der Uni F...               10380
                   Fakultät für Umwelt und Natürliche Ressourcen a...               10380
                   Medizinische Fakultät an der Uni Freiburg                        10380
...                                                                                   ...
834    Garching    Fakultät für Mathematik an der TU München/Garching               20967
                   Fakultät für Physik an der TU München/Garching                   20967
                   Munich School of Engineering an der TU München/...               20967
854    Senftenberg Fakultät 2: Umwelt und Naturwissenschaften an d...                4988
878    Wiesbaden   EBS Law School an der EBS Universität/Wiesbaden...                   0

                                                                       uni_total_master  \
id_uni fbs_city    fbs_name
2      Freiburg    Fakultät für Biologie an der Uni Freiburg                       5622
                   Fakultät für Chemie und Pharmazie an der Uni Fr...              5622
                   Fakultät für Mathematik und Physik an der Uni F...              5622
                   Fakultät für Umwelt und Natürliche Ressourcen a...              5622
                   Medizinische Fakultät an der Uni Freiburg                       5622
...                                                                                 ...
834    Garching    Fakultät für Mathematik an der TU München/Garching             18419
                   Fakultät für Physik an der TU München/Garching                 18419
                   Munich School of Engineering an der TU München/...             18419
854    Senftenberg Fakultät 2: Umwelt und Naturwissenschaften an d...              1847
878    Wiesbaden   EBS Law School an der EBS Universität/Wiesbaden...               330

                                                                       uni_total_lehramt  \
id_uni fbs_city    fbs_name
2      Freiburg    Fakultät für Biologie an der Uni Freiburg                        1201
                   Fakultät für Chemie und Pharmazie an der Uni Fr...               1201
                   Fakultät für Mathematik und Physik an der Uni F...               1201
                   Fakultät für Umwelt und Natürliche Ressourcen a...               1201
                   Medizinische Fakultät an der Uni Freiburg                        1201
...                                                                                  ...

In [110]:
uni_fbs3 = get_data('SELECT * FROM tomorrows_talents.uni_fbs2')

In [127]:
uni_fbs3.groupby('uni_city').sum('fbs_total_stud')['fbs_total_stud']

uni_city
Aachen                       31250.0
Aalen                        3010.0
Alfter                       860.0
Ansbach                      1010.0
Aschaffenburg                3310.0
Augsburg                     17600.0
Bamberg                      9470.0
Bayreuth                     12510.0
Berlin                       90660.0
Biberach                     1000.0
Bielefeld                    24870.0
Bingen                       1390.0
Bochum                       39800.0
Bonn                         25160.0
Brandenburg                  2400.0
Braunschweig                 14510.0
Breitenbrunn / Erzgebirge    0.0
Bremen                       20140.0
Bremerhaven                  1960.0
Brühl                        870.0
Buxtehude                    370.0
Clausthal                    2270.0
Coburg                       2770.0
Cottbus                      2440.0
Darmstadt                    25040.0
Dortmund                     34240.0
Dresden                      19310.0
Duisburg                     10270.0
Düsseldorf                   31920.0
Eberswalde                   830.0
Eichstätt                    2960.0
Emden                        3760.0
Erfurt                       2190.0
Erlangen                     21690.0
Essen                        21710.0
Esslingen                    2950.0
Flensburg                    2170.0
Frankfurt                    50020.0
Freiberg                     1630.0
Freiburg                     17880.0
Freising-Weihenstephan       420.0
Friedrichshafen              530.0
Fulda                        5680.0
Furtwangen                   2200.0
Garching                     11030.0
Gelsenkirchen                4040.0
Gießen                       29050.0
Glauchau                     0.0
Greifswald                   8360.0
Göttingen                    24350.0
Halle                        15700.0
Hamburg                      42760.0
Hamm                         580.0
Hannover                     25110.0
Heidelberg                   24290.0
Heilbronn                    5010.0
Hildesheim                   6860.0
Hof                          2280.0
Idstein                      480.0
Ilmenau                      2160.0
Ingolstadt                   850.0
Iserlohn                     770.0
Jena                         18870.0
Kaiserslautern               6220.0
Karlsruhe                    17340.0
Kassel                       14560.0
Kempten                      9140.0
Kiel                         26710.0
Koblenz                      9120.0
Konstanz                     13390.0
Krefeld                      2950.0
Kurpark                      230.0
Kutzschenstein               0.0
Köln                         55080.0
Köthen                       1270.0
Landstraße                   1790.0
Leipzig                      22000.0
Lemgo                        1340.0
Lübeck                       6800.0
Lüneburg                     4380.0
Magdeburg                    10070.0
Mainz                        27340.0
Mannheim                     17590.0
Marburg                      18670.0
Merseburg                    1420.0
Mittweida                    2860.0
Mülheim an der Ruhr          2980.0
München                      66460.0
Münster                      41760.0
Neubrandenburg               1060.0
Neuruppin                    520.0
Nürnberg                     18410.0
Nürtingen                    1640.0
Offenburg                    890.0
Oldenburg                    14050.0
Osnabrück                    6990.0
Ottersberg                   10.0
Paderborn                    13900.0
Passau                       7400.0
Pforzheim                    4680.0
Plauen                       0.0
Potsdam                      18070.0
Regensburg                   26170.0
Reichartshausen              1510.0
Reutlingen                   3810.0
Rosenheim                    3270.0
Rostock                      8240.0
Rödermark                    0.0
Saarbrücken                  10950.0
Schmalkalden                 1490.0
Senftenberg                  420.0
Siegen                       16730.0
Sigmaringen                  710.0
Stralsund                    2100.0
Straße                       1120.0
Stuttgart                    20110.0
Trier                        9830.0
Tübingen                     21970.0
Ulm                          12460.0
Vallendar                    1670.0
Wedel                        1340.0
Weimar                       1270.0
Weingarten                   2380.0
Wernigerode                  1710.0
Wiesbaden                    7480.0
Wildau                       2070.0
Wismar                       4550.0
Witten                       2480.0
Wolfenbüttel                 4970.0
Worms                        6700.0
Wuppertal                    12960.0
Würzburg                     20200.0
Zittau                       630.0
Zwickau                      1700.0
Name: fbs_total_stud, dtype: float64

In [112]:
def definer_mg(x):
    x = x.lower() 
    if  (x.find('medic') > -1 or x.find('mediz') > -1 or x.find('gesund') > -1 or x.find('pharma') > -1 or x.find('spo') > -1
    or x.find('psy') > -1 or x.find('human') > -1 or x.find('lebenswis') > -1 or x.find('pflege') > -1
    or x.find('fachbereich i an der uni trier') > -1 or x.find('life science') > -1 or x.find('nursing') > -1
    or x.find('fakultät v an der hs hannover') > -1):
        return 1
    else:
        return 0
def definer_mn(x):
    x = x.lower() 
    if (x.find('math') > -1 or x.find('phy') > -1 or x.find('chem') > -1 or x.find('bio') > -1 or x.find('mint') > -1 or x.find('natur') > -1
    or x.find('geo') > -1 or x.find('techno') > -1 or x.find('technik') > -1 or x.find('fachbereich 4 an der hs ruhr west/mülheim') > -1
    or x.find('fachbereich iv an der uni trier') > -1 or x.find('carl-friedrich-gauß-fakultät') > -1
    or x.find('fakultät graduate school an der hs esslingen') > -1):
        return 1
    else:
        return 0
def definer_rws(x): 
    x = x.lower() 
    if (x.find('wirt') > -1 or x.find('sozial') > -1 or x.find('recht') > -1  or x.find('jur') > -1  or x.find('betr') > -1 or x.find('gese') > -1 or x.find('pol') > -1  or x.find('verwa') > -1 or x.find('vertr') > -1 
        or x.find('geist') > -1 or x.find('volksw') > -1 or x.find('bwl') > -1 or x.find('touri') > -1 or x.find('bildung') > -1 or x.find('business') > -1 or x.find('management') > -1 
        or x.find('fachbereich 2 an der hs bremerhaven') > -1 or x.find('fachbereich 2 an der hs ruhr west/mülheim') > -1
        or x.find('logistik') > -1 or x.find('fachbereich i an der uni trier') > -1 or x.find('fachbereich iii an der uni trier') > -1
        or x.find('fachbereich iv an der uni trier') > -1 or x.find('erziehungs') > -1 or x.find('medien') > -1
        or x.find('carl-friedrich-gauß-fakultät') > -1 or x.find('soziologie') > -1 or x.find('fakultät graduate school an der hs esslingen') > -1
        or x.find('heilbronn university graduate school') > -1 or x.find('textil') > -1 or x.find('fakultät v an der hs hannover') > -1
        or x.find('fakultäten i und ii an der karlshochschule int') > -1 or x.find('industrielle') > -1 or x.find('law school') > -1
        or x.find('nachhaltigkeit') > -1 or x.find('fakultäten i und ii an der karlshochschule int. univ. (priv.)') > -1):
        return 1
    else:
        return 0
def definer_sk(x):
    x = x.lower()  
    if (x.find('engl') > -1 or x.find('eng.') > -1 or x.find('eng-') > -1 or x.find('phil') > -1 or x.find('phil') > -1
    or x.find('franz') > -1 or x.find('amer') > -1 or x.find('angl') > -1  or x.find('jap') > -1 or x.find('asia') > -1
    or x.find('lingu') > -1 or x.find('kultur') > -1 or x.find('literat') > -1 or x.find('germanistik') > -1
    or x.find('fachbereich i an der uni trier') > -1 or x.find('fachbereich ii an der uni trier') > -1
    or x.find('fachbereich iii an der uni trier') > -1 or x.find('asien') > -1 or x.find('gestaltung') > -1):
        return 1
    else:
        return 0
def definer_ii(x):
    x = x.lower() 
    if  (x.find('ingenieur') > -1 or x.find('info') > -1 or x.find('tech') > -1 or x.find('masch') > -1 or x.find('elektro') > -1
    or x.find('archit') > -1 or x.find('bau') > -1 or x.find('luft') > -1 or x.find('raum') > -1 or x.find('scitec') > -1
    or x.find('peter behrens school of arts an der hs düsseldorf') > -1 or x.find('fachbereich 3 an der hs ruhr west/mülheim') > -1
    or x.find('fachbereich 4 an der hs ruhr west/mülheim') > -1 or x.find('fachbereich iv') > -1 or x.find('umwelt') > -1
    or x.find('prozesswissenschaften') > -1 or x.find('carl-friedrich-gauß-fakultät') > -1 or x.find('enginee') > -1
    or x.find('mechatron') > -1 or x.find('fakultät graduate school an der hs esslingen') > -1 or x.find('fakultät design an der haw coburg') > -1
    or x.find('fakultät gestaltung an der hs wismar') > -1 or x.find('fahrzeug') > -1 or x.find('fachbereich 2 an der th bingen') > -1
    or x.find('digital') > -1 or x.find('duale studiengänge an der hochschule 21/buxtehude') > -1 or x.find('industrielle') > -1):
        return 1
    else:
        return 0

In [113]:
uni_fbs3['fbs_med_d'] = uni_fbs3['fbs_name'].apply(lambda x: definer_mg(x))
uni_fbs3['fbs_nat_d'] = uni_fbs3['fbs_name'].apply(lambda x: definer_mn(x))
uni_fbs3['fbs_rws_d'] = uni_fbs3['fbs_name'].apply(lambda x: definer_rws(x))
uni_fbs3['fbs_spr_d'] = uni_fbs3['fbs_name'].apply(lambda x: definer_sk(x))
uni_fbs3['fbs_ing_d'] = uni_fbs3['fbs_name'].apply(lambda x: definer_ii(x))

In [114]:
uni_fbs3['fbs_sonst'] = uni_fbs3[['fbs_med_d','fbs_nat_d','fbs_rws_d','fbs_spr_d','fbs_ing_d']].apply(lambda x: 0 if x.fbs_med_d + x.fbs_nat_d + x.fbs_rws_d + x.fbs_spr_d + x.fbs_ing_d > 0 else 1, axis = 1)
uni_fbs3['fbs_sonst'].value_counts()
uni_fbs3[uni_fbs3['fbs_sonst']==1].count()

index                                 0
id_uni                                0
id_fak                                0
fbs_name                              0
fbs_city                              0
fbs_street_nr                         0
fbs_plz                               0
fbs_total_stud                        0
fbs_total_stud_ma                     0
fbs_support_start                     0
fbs_tframe_grad_ba                    0
fbs_tframe_grad_ma                    0
fbs_lon                               0
fbs_lat                               0
fbs_int_ba                            0
fbs_int_ma                            0
fbs_foreign_spot                      0
fbs_sup_doz                           0
fbs_sup_in_studies                    0
fbs_curriculum                        0
fbs_students_orga                     0
fbs_exams                             0
fbs_research_conn                     0
fbs_offer_joborientation              0
fbs_supp_exchange                     0
fbs_faculties                         0
fbs_bib                               0
fbs_it_infrastructure                 0
fbs_grade_overall                     0
fbs_total_students_la                 0
fbs_total_students_ma_appr            0
fbs_med_d                             0
fbs_nat_d                             0
fbs_rws_d                             0
fbs_spr_d                             0
fbs_ing_d                             0
fbs_sonst                             0
uni_name                              0
uni_city                              0
uni_street_nr                         0
uni_plz                               0
uni_homepage                          0
uni_type                              0
uni_traeger                           0
uni_total_students                    0
uni_total_students_loc                0
uni_lon                               0
uni_lat                               0
uni_med_ges_percentage                0
uni_nat_math_percentage               0
uni_law_econ_social_percentage        0
uni_lang_cult_percentage              0
uni_engineer_inf_percentage           0
uni_other_percentage                  0
uni_bachelor_percentage               0
uni_master_percentage                 0
uni_lehramt_percentage                0
uni_dipl_magis_staatsex_percentage    0
uni_other_percentage_grad             0
uni_total_med_ges                     0
uni_total_nat_math                    0
uni_total_law_econ_social             0
uni_total_lang_cult                   0
uni_total_engineer_info               0
uni_total_other                       0
uni_total_bachelor                    0
uni_total_master                      0
uni_total_lehramt                     0
uni_total_dipl_magis_staatsex         0
uni_total_other_grad                  0
dtype: int64

In [115]:
uni_fbs3[uni_fbs3['fbs_name'] == 'Fachbereich IV an der Uni Trier']

,index,id_uni,id_fak,fbs_name,fbs_city,fbs_street_nr,fbs_plz,fbs_total_stud,fbs_total_stud_ma,fbs_support_start,fbs_tframe_grad_ba,fbs_tframe_grad_ma,fbs_lon,fbs_lat,fbs_int_ba,fbs_int_ma,fbs_foreign_spot,fbs_sup_doz,fbs_sup_in_studies,fbs_curriculum,fbs_students_orga,fbs_exams,fbs_research_conn,fbs_offer_joborientation,fbs_supp_exchange,fbs_faculties,fbs_bib,fbs_it_infrastructure,fbs_grade_overall,fbs_total_students_la,fbs_total_students_ma_appr,fbs_med_d,fbs_nat_d,fbs_rws_d,fbs_spr_d,fbs_ing_d,fbs_sonst,uni_name,uni_city,uni_street_nr,uni_plz,uni_homepage,uni_type,uni_traeger,uni_total_students,uni_total_students_loc,uni_lon,uni_lat,uni_med_ges_percentage,uni_nat_math_percentage,uni_law_econ_social_percentage,uni_lang_cult_percentage,uni_engineer_inf_percentage,uni_other_percentage,uni_bachelor_percentage,uni_master_percentage,uni_lehramt_percentage,uni_dipl_magis_staatsex_percentage,uni_other_percentage_grad,uni_total_med_ges,uni_total_nat_math,uni_total_law_econ_social,uni_total_lang_cult,uni_total_engineer_info,uni_total_other,uni_total_bachelor,uni_total_master,uni_total_lehramt,uni_total_dipl_magis_staatsex,uni_total_other_grad
226,987,132,400166,Fachbereich IV an der Uni Trier,Trier,Universitätsring 15,54286,610.0,130.0,0.571429,0.75,0.571,6.682927,49.745735,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,170.0,0,1,1,0,1,0,Universität Trier,Trier,Universitätsring 15,54286,https://www.uni-trier.de,Universität,öffentlich,12175.0,12175.0,6.682927,49.745735,0.017,0.12,0.547,0.263,0.044,0.008,0.437,0.194,0.158,0.165,0.046,206,1461,6659,3202,535,97,5320,2361,1923,2008,560

In [118]:
uni_fbs3.duplicated('id_fak').value_counts()

False    1143
dtype: int64

In [116]:
import psycopg2
from sql import host, port, database, user, password, engine
#Specify which table within your database you want to push your data to. Give your table an unambiguous name.
table_name = 'uni_fbs2'
# If the specified table doesn't exist yet, it will be created
# With 'replace', your data will be replaced if the table already exists.
# This will take a minute or two...
# Write records stored in a dataframe to SQL database
if engine!=None:
    try:
        #df_selected_airports
        uni_fbs3.to_sql(name=table_name, # Name of SQL table
                        con=engine, # Engine or connection
                        if_exists='replace', # Drop the table before inserting new values 
                        schema='tomorrows_talents', # Use schmea that was defined earlier
                        index=False, # Write DataFrame index as a column
                        chunksize=5000, # Specify the number of rows in each batch to be written at a time
                        method='multi') # Pass multiple values in a single INSERT clause
        print(f"The {table_name} table was imported successfully.")
    # Error handling
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
        engine = None

The uni_fbs2 table was imported successfully.